/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentAsyncTaskSync : AgentAsyncTaskSync 的公开协议结构。 / Public contract for agent async task sync.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentAsyncTaskSync {
    /// 字段 activeTasks / active tasks field。
    #[serde(rename = "activeTasks")]
    pub active_tasks: Vec<models::AsyncTask>,
    /// 字段 notificationMessages / notification messages field。
    #[serde(rename = "notificationMessages")]
    pub notification_messages: Vec<models::ConversationMessage>,
    /// 字段 nextMessageId / next message id field。
    #[serde(rename = "nextMessageId", deserialize_with = "Option::deserialize")]
    pub next_message_id: Option<String>,
    /// 字段 hasMore / has more field。
    #[serde(rename = "hasMore")]
    pub has_more: bool,
    /// 字段 pollingRequired / polling required field。
    #[serde(rename = "pollingRequired")]
    pub polling_required: bool,
}

impl AgentAsyncTaskSync {
    /// AgentAsyncTaskSync 的公开协议结构。 / Public contract for agent async task sync.
    pub fn new(
        active_tasks: Vec<models::AsyncTask>,
        notification_messages: Vec<models::ConversationMessage>,
        next_message_id: Option<String>,
        has_more: bool,
        polling_required: bool,
    ) -> AgentAsyncTaskSync {
        AgentAsyncTaskSync {
            active_tasks,
            notification_messages,
            next_message_id,
            has_more,
            polling_required,
        }
    }
}
