/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentsConfig : AgentsConfig 的公开协议结构。 / Public contract for agents config.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentsConfig {
    /// 字段 modelConfig / model config field。
    #[serde(rename = "modelConfig")]
    pub model_config: Box<models::ModelConfig>,
    /// 字段 supportAttachmentExt / support attachment ext field。
    #[serde(rename = "supportAttachmentExt")]
    pub support_attachment_ext: Vec<models::AttachmentExtension>,
    /// 字段 maxAttachmentCount / max attachment count field。
    #[serde(rename = "maxAttachmentCount")]
    pub max_attachment_count: i32,
}

impl AgentsConfig {
    /// AgentsConfig 的公开协议结构。 / Public contract for agents config.
    pub fn new(
        model_config: models::ModelConfig,
        support_attachment_ext: Vec<models::AttachmentExtension>,
        max_attachment_count: i32,
    ) -> AgentsConfig {
        AgentsConfig {
            model_config: Box::new(model_config),
            support_attachment_ext,
            max_attachment_count,
        }
    }
}
