/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentFile : AgentFile 的公开协议结构。 / Public contract for agent file.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentFile {
    /// 字段 id / id field。
    #[serde(rename = "id")]
    pub id: i64,
    /// 文件名 / file name。
    #[serde(rename = "fileName")]
    pub file_name: String,
    /// 字段 contentMd5 / content md5 field。
    #[serde(rename = "contentMd5")]
    pub content_md5: String,
    /// 大小（字节）或分页容量 / byte size or page size。
    #[serde(rename = "size")]
    pub size: i64,
    /// 创建时间 / creation time。
    #[serde(rename = "createdTime")]
    pub created_time: chrono::DateTime<chrono::FixedOffset>,
    /// 最后更新时间 / last update time。
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
}

impl AgentFile {
    /// AgentFile 的公开协议结构。 / Public contract for agent file.
    pub fn new(
        id: i64,
        file_name: String,
        content_md5: String,
        size: i64,
        created_time: chrono::DateTime<chrono::FixedOffset>,
        last_update_time: chrono::DateTime<chrono::FixedOffset>,
    ) -> AgentFile {
        AgentFile {
            id,
            file_name,
            content_md5,
            size,
            created_time,
            last_update_time,
        }
    }
}
