/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatResponseBriefEvent : AiChatResponseBriefEvent 的公开协议结构。 / Public contract for ai chat response brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatResponseBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 assistantMessages / assistant messages field。
    #[serde(rename = "assistantMessages")]
    pub assistant_messages: Vec<models::AssistantChatMessage>,
    /// 字段 usage / usage field。
    #[serde(rename = "usage")]
    pub usage: Box<models::Usage>,
}

impl AiChatResponseBriefEvent {
    /// AiChatResponseBriefEvent 的公开协议结构。 / Public contract for ai chat response brief event.
    pub fn new(
        r#type: Type,
        assistant_messages: Vec<models::AssistantChatMessage>,
        usage: models::Usage,
    ) -> AiChatResponseBriefEvent {
        AiChatResponseBriefEvent {
            r#type,
            assistant_messages,
            usage: Box::new(usage),
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "chat-client-response")]
    ChatClientResponse,
}

impl Default for Type {
    fn default() -> Type {
        Self::ChatClientResponse
    }
}
