/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatMessageEvent : AiChatMessageEvent 的公开协议结构。 / Public contract for ai chat message event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatMessageEvent {
    /// 消息 ID / message ID。
    #[serde(rename = "messageId")]
    pub message_id: String,
    /// 字段 events / events field。
    #[serde(rename = "events")]
    pub events: Vec<models::AiChatBriefEvent>,
}

impl AiChatMessageEvent {
    /// AiChatMessageEvent 的公开协议结构。 / Public contract for ai chat message event.
    pub fn new(message_id: String, events: Vec<models::AiChatBriefEvent>) -> AiChatMessageEvent {
        AiChatMessageEvent { message_id, events }
    }
}
