/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatRequestBriefEvent : AiChatRequestBriefEvent 的公开协议结构。 / Public contract for ai chat request brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatRequestBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 messages / messages field。
    #[serde(rename = "messages")]
    pub messages: Vec<models::ChatMessage>,
    /// 字段 chatOptions / chat options field。
    #[serde(
        rename = "chatOptions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub chat_options: Option<Option<Box<models::ChatOptions>>>,
}

impl AiChatRequestBriefEvent {
    /// AiChatRequestBriefEvent 的公开协议结构。 / Public contract for ai chat request brief event.
    pub fn new(r#type: Type, messages: Vec<models::ChatMessage>) -> AiChatRequestBriefEvent {
        AiChatRequestBriefEvent {
            r#type,
            messages,
            chat_options: None,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "chat-client-request")]
    ChatClientRequest,
}

impl Default for Type {
    fn default() -> Type {
        Self::ChatClientRequest
    }
}
