/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatCompactorWarningBriefEvent : AiChatCompactorWarningBriefEvent 的公开协议结构。 / Public contract for ai chat compactor warning brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatCompactorWarningBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 level / level field。
    #[serde(rename = "level")]
    pub level: String,
    /// 字段 warning / warning field。
    #[serde(rename = "warning")]
    pub warning: String,
}

impl AiChatCompactorWarningBriefEvent {
    /// AiChatCompactorWarningBriefEvent 的公开协议结构。 / Public contract for ai chat compactor warning brief event.
    pub fn new(r#type: Type, level: String, warning: String) -> AiChatCompactorWarningBriefEvent {
        AiChatCompactorWarningBriefEvent {
            r#type,
            level,
            warning,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "compactor-warning")]
    CompactorWarning,
}

impl Default for Type {
    fn default() -> Type {
        Self::CompactorWarning
    }
}
