/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatBriefEvent : AiChatBriefEvent 的公开协议结构。 / Public contract for ai chat brief event.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AiChatBriefEvent {
    #[serde(rename = "user-query")]
    UserQuery(Box<models::AiChatUserQueryBriefEvent>),
    #[serde(rename = "compressor-context-start")]
    CompressorContextStart(Box<models::AiChatCompressorContextStartBriefEvent>),
    #[serde(rename = "compressor-context-end")]
    CompressorContextEnd(Box<models::AiChatCompressorContextEndBriefEvent>),
    #[serde(rename = "compactor-warning")]
    CompactorWarning(Box<models::AiChatCompactorWarningBriefEvent>),
    #[serde(rename = "manual-interrupt")]
    ManualInterrupt(Box<models::AiChatManualInterruptBriefEvent>),
    #[serde(rename = "error")]
    Error(Box<models::AiChatErrorBriefEvent>),
    #[serde(rename = "start")]
    Start(Box<models::AiChatStartBriefEvent>),
    #[serde(rename = "think")]
    Think(Box<models::AiChatThinkBriefEvent>),
    #[serde(rename = "chat-client-request")]
    ChatClientRequest(Box<models::AiChatRequestBriefEvent>),
    #[serde(rename = "chat-client-response")]
    ChatClientResponse(Box<models::AiChatResponseBriefEvent>),
    #[serde(rename = "message")]
    Message(Box<models::AiChatMessageBriefEvent>),
    #[serde(rename = "tool-execution")]
    ToolExecution(Box<models::AiChatToolExecutionBriefEvent>),
    #[serde(rename = "tool-execution-sub-agent-call")]
    ToolExecutionSubAgentCall(Box<models::AiChatSubAgentCallBriefEvent>),
    #[serde(rename = "tool-execution-awaiting-user-input")]
    ToolExecutionAwaitingUserInput(Box<models::AiChatAwaitingInputBriefEvent>),
    #[serde(rename = "end")]
    End(Box<models::AiChatEndBriefEvent>),
    #[serde(rename = "UnknownAiChatBriefEvent")]
    UnknownAiChatBriefEvent(Box<models::UnknownAiChatBriefEvent>),
}

impl Default for AiChatBriefEvent {
    fn default() -> Self {
        Self::UserQuery(Default::default())
    }
}
