/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatStreamInput : AiChatStreamInput 的公开协议结构。 / Public contract for ai chat stream input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatStreamInput {
    /// 消息 ID / message ID。
    #[serde(rename = "messageId")]
    pub message_id: String,
}

impl AiChatStreamInput {
    /// AiChatStreamInput 的公开协议结构。 / Public contract for ai chat stream input.
    pub fn new(message_id: String) -> AiChatStreamInput {
        AiChatStreamInput { message_id }
    }
}
