/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatToolExecutionBriefEvent : AiChatToolExecutionBriefEvent 的公开协议结构。 / Public contract for ai chat tool execution brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatToolExecutionBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 toolId / tool id field。
    #[serde(rename = "toolId")]
    pub tool_id: String,
    /// 字段 toolName / tool name field。
    #[serde(rename = "toolName")]
    pub tool_name: String,
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
    /// 字段 action / action field。
    #[serde(rename = "action")]
    pub action: String,
    /// 字段 summary / summary field。
    #[serde(
        rename = "summary",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub summary: Option<Option<String>>,
    /// 字段 extension / extension field。
    #[serde(
        rename = "extension",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub extension: Option<Option<Box<models::ToolExtension>>>,
}

impl AiChatToolExecutionBriefEvent {
    /// AiChatToolExecutionBriefEvent 的公开协议结构。 / Public contract for ai chat tool execution brief event.
    pub fn new(
        r#type: Type,
        tool_id: String,
        tool_name: String,
        status: String,
        action: String,
    ) -> AiChatToolExecutionBriefEvent {
        AiChatToolExecutionBriefEvent {
            r#type,
            tool_id,
            tool_name,
            status,
            action,
            summary: None,
            extension: None,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "tool-execution")]
    ToolExecution,
}

impl Default for Type {
    fn default() -> Type {
        Self::ToolExecution
    }
}
