/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatSubmission : AiChatSubmission 的公开协议结构。 / Public contract for ai chat submission.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatSubmission {
    /// 会话 ID / conversation ID。
    #[serde(rename = "conversationId")]
    pub conversation_id: String,
    /// 消息 ID / message ID。
    #[serde(rename = "messageId")]
    pub message_id: String,
    /// 字段 disposition / disposition field。 Dispatch disposition. Unknown future values must be preserved.
    #[serde(rename = "disposition")]
    pub disposition: String,
    /// 当前状态 / current status。 Persisted message status. Unknown future values must be preserved.
    #[serde(rename = "status")]
    pub status: String,
}

impl AiChatSubmission {
    /// AiChatSubmission 的公开协议结构。 / Public contract for ai chat submission.
    pub fn new(
        conversation_id: String,
        message_id: String,
        disposition: String,
        status: String,
    ) -> AiChatSubmission {
        AiChatSubmission {
            conversation_id,
            message_id,
            disposition,
            status,
        }
    }
}
