/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatEventsBatchSkipped : AiChatEventsBatchSkipped 的公开协议结构。 / Public contract for ai chat events batch skipped.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatEventsBatchSkipped {
    /// 消息 ID / message ID。
    #[serde(rename = "messageId")]
    pub message_id: String,
    /// 字段 reason / reason field。
    #[serde(rename = "reason")]
    pub reason: String,
}

impl AiChatEventsBatchSkipped {
    /// AiChatEventsBatchSkipped 的公开协议结构。 / Public contract for ai chat events batch skipped.
    pub fn new(message_id: String, reason: String) -> AiChatEventsBatchSkipped {
        AiChatEventsBatchSkipped { message_id, reason }
    }
}
