/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatStartBriefEvent : AiChatStartBriefEvent 的公开协议结构。 / Public contract for ai chat start brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatStartBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AiChatStartBriefEvent {
    /// AiChatStartBriefEvent 的公开协议结构。 / Public contract for ai chat start brief event.
    pub fn new(r#type: Type) -> AiChatStartBriefEvent {
        AiChatStartBriefEvent { r#type }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "start")]
    Start,
}

impl Default for Type {
    fn default() -> Type {
        Self::Start
    }
}
