/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatAwaitingInputBriefEvent : AiChatAwaitingInputBriefEvent 的公开协议结构。 / Public contract for ai chat awaiting input brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatAwaitingInputBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 toolCallId / tool call id field。
    #[serde(rename = "toolCallId")]
    pub tool_call_id: String,
    /// 字段 toolName / tool name field。
    #[serde(rename = "toolName")]
    pub tool_name: String,
    /// 字段 questionId / question id field。
    #[serde(rename = "questionId")]
    pub question_id: String,
    /// 字段 question / question field。
    #[serde(rename = "question")]
    pub question: String,
    /// 字段 options / options field。
    #[serde(rename = "options")]
    pub options: Vec<models::AskUserQuestionOption>,
    /// 字段 multiple / multiple field。
    #[serde(rename = "multiple")]
    pub multiple: bool,
    /// 字段 serverNow / server now field。
    #[serde(rename = "serverNow")]
    pub server_now: chrono::DateTime<chrono::FixedOffset>,
    /// 字段 timeoutSeconds / timeout seconds field。
    #[serde(rename = "timeoutSeconds")]
    pub timeout_seconds: i64,
    /// 字段 questionDetails / question details field。
    #[serde(
        rename = "questionDetails",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub question_details: Option<Option<String>>,
}

impl AiChatAwaitingInputBriefEvent {
    /// AiChatAwaitingInputBriefEvent 的公开协议结构。 / Public contract for ai chat awaiting input brief event.
    pub fn new(
        r#type: Type,
        tool_call_id: String,
        tool_name: String,
        question_id: String,
        question: String,
        options: Vec<models::AskUserQuestionOption>,
        multiple: bool,
        server_now: chrono::DateTime<chrono::FixedOffset>,
        timeout_seconds: i64,
    ) -> AiChatAwaitingInputBriefEvent {
        AiChatAwaitingInputBriefEvent {
            r#type,
            tool_call_id,
            tool_name,
            question_id,
            question,
            options,
            multiple,
            server_now,
            timeout_seconds,
            question_details: None,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "tool-execution-awaiting-user-input")]
    ToolExecutionAwaitingUserInput,
}

impl Default for Type {
    fn default() -> Type {
        Self::ToolExecutionAwaitingUserInput
    }
}
