/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatFileRef : AiChatFileRef 的公开协议结构。 / Public contract for ai chat file ref.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatFileRef {
    /// 字段 id / id field。
    #[serde(rename = "id")]
    pub id: i64,
    /// 文件名 / file name。
    #[serde(
        rename = "fileName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub file_name: Option<Option<String>>,
}

impl AiChatFileRef {
    /// AiChatFileRef 的公开协议结构。 / Public contract for ai chat file ref.
    pub fn new(id: i64) -> AiChatFileRef {
        AiChatFileRef {
            id,
            file_name: None,
        }
    }
}
