/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatEndBriefEvent : AiChatEndBriefEvent 的公开协议结构。 / Public contract for ai chat end brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatEndBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 executionTimeMillis / execution time millis field。
    #[serde(rename = "executionTimeMillis")]
    pub execution_time_millis: i64,
    /// 字段 totalUsage / total usage field。
    #[serde(rename = "totalUsage")]
    pub total_usage: Box<models::Usage>,
    /// 字段 messageContextUsageRatio / message context usage ratio field。
    #[serde(
        rename = "messageContextUsageRatio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub message_context_usage_ratio: Option<Option<f64>>,
    /// 字段 contextWindowUsage / context window usage field。
    #[serde(
        rename = "contextWindowUsage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub context_window_usage: Option<Option<Box<models::ConversationContextUsage>>>,
    /// 字段 artifacts / artifacts field。
    #[serde(rename = "artifacts")]
    pub artifacts: Vec<models::ArtifactInfo>,
    /// 字段 nonFileArtifacts / non file artifacts field。
    #[serde(rename = "nonFileArtifacts")]
    pub non_file_artifacts: Vec<models::WorkspaceNonFileArtifact>,
}

impl AiChatEndBriefEvent {
    /// AiChatEndBriefEvent 的公开协议结构。 / Public contract for ai chat end brief event.
    pub fn new(
        r#type: Type,
        execution_time_millis: i64,
        total_usage: models::Usage,
        artifacts: Vec<models::ArtifactInfo>,
        non_file_artifacts: Vec<models::WorkspaceNonFileArtifact>,
    ) -> AiChatEndBriefEvent {
        AiChatEndBriefEvent {
            r#type,
            execution_time_millis,
            total_usage: Box::new(total_usage),
            message_context_usage_ratio: None,
            context_window_usage: None,
            artifacts,
            non_file_artifacts,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "end")]
    End,
}

impl Default for Type {
    fn default() -> Type {
        Self::End
    }
}
