/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatCompressorContextStartBriefEvent : AiChatCompressorContextStartBriefEvent 的公开协议结构。 / Public contract for ai chat compressor context start brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatCompressorContextStartBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AiChatCompressorContextStartBriefEvent {
    /// AiChatCompressorContextStartBriefEvent 的公开协议结构。 / Public contract for ai chat compressor context start brief event.
    pub fn new(r#type: Type) -> AiChatCompressorContextStartBriefEvent {
        AiChatCompressorContextStartBriefEvent { r#type }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "compressor-context-start")]
    CompressorContextStart,
}

impl Default for Type {
    fn default() -> Type {
        Self::CompressorContextStart
    }
}
