/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatInput : AiChatInput 的公开协议结构。 / Public contract for ai chat input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatInput {
    /// 用户问题 / user query。
    #[serde(rename = "query")]
    pub query: String,
    /// 会话 ID / conversation ID。
    #[serde(
        rename = "conversationId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub conversation_id: Option<Option<String>>,
    /// 字段 chatModelSpec / chat model spec field。
    #[serde(
        rename = "chatModelSpec",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub chat_model_spec: Option<Option<Box<models::ChatModelSpec>>>,
    /// 字段 files / files field。
    #[serde(
        rename = "files",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub files: Option<Option<Vec<models::AiChatFileRef>>>,
}

impl AiChatInput {
    /// AiChatInput 的公开协议结构。 / Public contract for ai chat input.
    pub fn new(query: String) -> AiChatInput {
        AiChatInput {
            query,
            conversation_id: None,
            chat_model_spec: None,
            files: None,
        }
    }
}
