/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatThinkBriefEvent : AiChatThinkBriefEvent 的公开协议结构。 / Public contract for ai chat think brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatThinkBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 消息正文 / message text。
    #[serde(rename = "message")]
    pub message: String,
}

impl AiChatThinkBriefEvent {
    /// AiChatThinkBriefEvent 的公开协议结构。 / Public contract for ai chat think brief event.
    pub fn new(r#type: Type, message: String) -> AiChatThinkBriefEvent {
        AiChatThinkBriefEvent { r#type, message }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "think")]
    Think,
}

impl Default for Type {
    fn default() -> Type {
        Self::Think
    }
}
