/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatEndBriefEvent : AiChatEndBriefEvent 的公开协议结构。 / Public contract for ai chat end brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatEndBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 executionTimeMillis / execution time millis field。
    #[serde(rename = "executionTimeMillis")]
    pub execution_time_millis: i64,
    /// 字段 totalUsage / total usage field。
    #[serde(rename = "totalUsage")]
    pub total_usage: Box<models::Usage>,
    /// 字段 messageContextUsageRatio / message context usage ratio field。
    #[serde(
        rename = "messageContextUsageRatio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub message_context_usage_ratio: Option<Option<f64>>,
    /// 字段 contextWindowUsage / context window usage field。
    #[serde(
        rename = "contextWindowUsage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub context_window_usage: Option<Option<Box<models::ConversationContextUsage>>>,
    /// 字段 artifacts / artifacts field。
    #[serde(rename = "artifacts")]
    pub artifacts: Vec<models::ArtifactInfo>,
    /// 字段 nonFileArtifacts / non file artifacts field。
    #[serde(rename = "nonFileArtifacts")]
    pub non_file_artifacts: Vec<models::WorkspaceNonFileArtifact>,
}

impl AiChatEndBriefEvent {
    /// AiChatEndBriefEvent 的公开协议结构。 / Public contract for ai chat end brief event.
    pub fn new(
        r#type: Type,
        execution_time_millis: i64,
        total_usage: models::Usage,
        artifacts: Vec<models::ArtifactInfo>,
        non_file_artifacts: Vec<models::WorkspaceNonFileArtifact>,
    ) -> AiChatEndBriefEvent {
        AiChatEndBriefEvent {
            r#type,
            execution_time_millis,
            total_usage: Box::new(total_usage),
            message_context_usage_ratio: None,
            context_window_usage: None,
            artifacts,
            non_file_artifacts,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "end")]
    End,
}

impl Default for Type {
    fn default() -> Type {
        Self::End
    }
}
