/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatEventsBatch : AiChatEventsBatch 的公开协议结构。 / Public contract for ai chat events batch.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatEventsBatch {
    /// 记录列表 / records。
    #[serde(rename = "records")]
    pub records: Vec<models::AiChatMessageEvent>,
    /// 字段 skipped / skipped field。
    #[serde(rename = "skipped")]
    pub skipped: Vec<models::AiChatEventsBatchSkipped>,
}

impl AiChatEventsBatch {
    /// AiChatEventsBatch 的公开协议结构。 / Public contract for ai chat events batch.
    pub fn new(
        records: Vec<models::AiChatMessageEvent>,
        skipped: Vec<models::AiChatEventsBatchSkipped>,
    ) -> AiChatEventsBatch {
        AiChatEventsBatch { records, skipped }
    }
}
