/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatUserQueryBriefEvent : AiChatUserQueryBriefEvent 的公开协议结构。 / Public contract for ai chat user query brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatUserQueryBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 用户问题 / user query。
    #[serde(rename = "query")]
    pub query: String,
    /// 字段 attachments / attachments field。
    #[serde(
        rename = "attachments",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub attachments: Option<Option<Vec<models::MediaAttachment>>>,
}

impl AiChatUserQueryBriefEvent {
    /// AiChatUserQueryBriefEvent 的公开协议结构。 / Public contract for ai chat user query brief event.
    pub fn new(r#type: Type, query: String) -> AiChatUserQueryBriefEvent {
        AiChatUserQueryBriefEvent {
            r#type,
            query,
            attachments: None,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "user-query")]
    UserQuery,
}

impl Default for Type {
    fn default() -> Type {
        Self::UserQuery
    }
}
