/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatBriefEventList : AiChatBriefEventList 的公开协议结构。 / Public contract for ai chat brief event list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatBriefEventList {
    /// 记录列表 / records。
    #[serde(rename = "records")]
    pub records: Vec<models::AiChatBriefEvent>,
}

impl AiChatBriefEventList {
    /// AiChatBriefEventList 的公开协议结构。 / Public contract for ai chat brief event list.
    pub fn new(records: Vec<models::AiChatBriefEvent>) -> AiChatBriefEventList {
        AiChatBriefEventList { records }
    }
}
