/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiChatSubAgentCallBriefEvent : AiChatSubAgentCallBriefEvent 的公开协议结构。 / Public contract for ai chat sub agent call brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatSubAgentCallBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 toolCallId / tool call id field。
    #[serde(rename = "toolCallId")]
    pub tool_call_id: String,
    /// 字段 toolName / tool name field。
    #[serde(rename = "toolName")]
    pub tool_name: String,
    /// 字段 subAgentConversationId / sub agent conversation id field。
    #[serde(rename = "subAgentConversationId")]
    pub sub_agent_conversation_id: String,
    /// 字段 subAgentMessageId / sub agent message id field。
    #[serde(rename = "subAgentMessageId")]
    pub sub_agent_message_id: String,
}

impl AiChatSubAgentCallBriefEvent {
    /// AiChatSubAgentCallBriefEvent 的公开协议结构。 / Public contract for ai chat sub agent call brief event.
    pub fn new(
        r#type: Type,
        tool_call_id: String,
        tool_name: String,
        sub_agent_conversation_id: String,
        sub_agent_message_id: String,
    ) -> AiChatSubAgentCallBriefEvent {
        AiChatSubAgentCallBriefEvent {
            r#type,
            tool_call_id,
            tool_name,
            sub_agent_conversation_id,
            sub_agent_message_id,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "tool-execution-sub-agent-call")]
    ToolExecutionSubAgentCall,
}

impl Default for Type {
    fn default() -> Type {
        Self::ToolExecutionSubAgentCall
    }
}
