/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ArtifactInfo : ArtifactInfo 的公开协议结构。 / Public contract for artifact info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtifactInfo {
    /// 文件 ID / file ID。
    #[serde(rename = "fileId")]
    pub file_id: i64,
    /// 字段 fileSize / file size field。
    #[serde(rename = "fileSize")]
    pub file_size: i64,
    /// 文件名 / file name。
    #[serde(rename = "fileName")]
    pub file_name: String,
    /// MIME 类型 / MIME type。
    #[serde(rename = "mimeType")]
    pub mime_type: String,
    /// 字段 relativePath / relative path field。
    #[serde(
        rename = "relativePath",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub relative_path: Option<Option<String>>,
    /// 字段 deliveryStatus / delivery status field。
    #[serde(rename = "deliveryStatus")]
    pub delivery_status: String,
    /// 字段 issueCodes / issue codes field。
    #[serde(rename = "issueCodes")]
    pub issue_codes: Vec<String>,
    /// 字段 recoverable / recoverable field。
    #[serde(rename = "recoverable")]
    pub recoverable: bool,
}

impl ArtifactInfo {
    /// ArtifactInfo 的公开协议结构。 / Public contract for artifact info.
    pub fn new(
        file_id: i64,
        file_size: i64,
        file_name: String,
        mime_type: String,
        delivery_status: String,
        issue_codes: Vec<String>,
        recoverable: bool,
    ) -> ArtifactInfo {
        ArtifactInfo {
            file_id,
            file_size,
            file_name,
            mime_type,
            relative_path: None,
            delivery_status,
            issue_codes,
            recoverable,
        }
    }
}
