/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AskUserQuestionExtensionContent : AskUserQuestionExtensionContent 的公开协议结构。 / Public contract for ask user question extension content.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AskUserQuestionExtensionContent {
    /// 字段 selectedOptions / selected options field。
    #[serde(rename = "selectedOptions")]
    pub selected_options: Vec<String>,
    /// 字段 customInput / custom input field。
    #[serde(
        rename = "customInput",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_input: Option<Option<String>>,
}

impl AskUserQuestionExtensionContent {
    /// AskUserQuestionExtensionContent 的公开协议结构。 / Public contract for ask user question extension content.
    pub fn new(selected_options: Vec<String>) -> AskUserQuestionExtensionContent {
        AskUserQuestionExtensionContent {
            selected_options,
            custom_input: None,
        }
    }
}
