/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AskUserQuestionOption : AskUserQuestionOption 的公开协议结构。 / Public contract for ask user question option.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AskUserQuestionOption {
    /// 字段 text / text field。
    #[serde(rename = "text")]
    pub text: String,
    /// 字段 recommended / recommended field。
    #[serde(rename = "recommended")]
    pub recommended: bool,
}

impl AskUserQuestionOption {
    /// AskUserQuestionOption 的公开协议结构。 / Public contract for ask user question option.
    pub fn new(text: String, recommended: bool) -> AskUserQuestionOption {
        AskUserQuestionOption { text, recommended }
    }
}
