/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AsyncTask : AsyncTask 的公开协议结构。 / Public contract for async task.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AsyncTask {
    /// 异步任务 ID / asynchronous task ID。
    #[serde(rename = "taskId")]
    pub task_id: String,
    /// 字段 taskType / task type field。
    #[serde(rename = "taskType")]
    pub task_type: String,
    /// 标题 / title。
    #[serde(rename = "title")]
    pub title: String,
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
    /// 字段 progressPercent / progress percent field。
    #[serde(
        rename = "progressPercent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub progress_percent: Option<Option<i32>>,
    /// 字段 phase / phase field。
    #[serde(
        rename = "phase",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phase: Option<Option<String>>,
    /// 字段 statusMessage / status message field。
    #[serde(
        rename = "statusMessage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status_message: Option<Option<String>>,
    /// 字段 resultAvailable / result available field。
    #[serde(rename = "resultAvailable")]
    pub result_available: bool,
    /// 字段 cancellable / cancellable field。
    #[serde(rename = "cancellable")]
    pub cancellable: bool,
    /// 字段 failureCode / failure code field。
    #[serde(
        rename = "failureCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub failure_code: Option<Option<String>>,
    /// 字段 failureMessage / failure message field。
    #[serde(
        rename = "failureMessage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub failure_message: Option<Option<String>>,
    /// 字段 originConversationId / origin conversation id field。
    #[serde(rename = "originConversationId")]
    pub origin_conversation_id: String,
    /// 字段 originMessageId / origin message id field。
    #[serde(rename = "originMessageId")]
    pub origin_message_id: String,
    /// 字段 originToolId / origin tool id field。
    #[serde(rename = "originToolId")]
    pub origin_tool_id: String,
    /// 字段 originToolName / origin tool name field。
    #[serde(rename = "originToolName")]
    pub origin_tool_name: String,
    /// 字段 targetMessageId / target message id field。
    #[serde(rename = "targetMessageId")]
    pub target_message_id: String,
    /// 字段 notificationStatus / notification status field。
    #[serde(rename = "notificationStatus")]
    pub notification_status: String,
    /// 字段 notificationMessageId / notification message id field。
    #[serde(
        rename = "notificationMessageId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notification_message_id: Option<Option<String>>,
    /// 创建时间 / creation time。
    #[serde(rename = "createdTime")]
    pub created_time: chrono::DateTime<chrono::FixedOffset>,
    /// 字段 startedTime / started time field。
    #[serde(
        rename = "startedTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub started_time: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// 字段 completedTime / completed time field。
    #[serde(
        rename = "completedTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub completed_time: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// 最后更新时间 / last update time。
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
    /// 字段 trackingStatus / tracking status field。
    #[serde(rename = "trackingStatus")]
    pub tracking_status: String,
    /// 字段 trackingFailureCode / tracking failure code field。
    #[serde(
        rename = "trackingFailureCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tracking_failure_code: Option<Option<String>>,
    /// 字段 lastPollError / last poll error field。
    #[serde(
        rename = "lastPollError",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_poll_error: Option<Option<String>>,
}

impl AsyncTask {
    /// AsyncTask 的公开协议结构。 / Public contract for async task.
    pub fn new(
        task_id: String,
        task_type: String,
        title: String,
        status: String,
        result_available: bool,
        cancellable: bool,
        origin_conversation_id: String,
        origin_message_id: String,
        origin_tool_id: String,
        origin_tool_name: String,
        target_message_id: String,
        notification_status: String,
        created_time: chrono::DateTime<chrono::FixedOffset>,
        last_update_time: chrono::DateTime<chrono::FixedOffset>,
        tracking_status: String,
    ) -> AsyncTask {
        AsyncTask {
            task_id,
            task_type,
            title,
            status,
            progress_percent: None,
            phase: None,
            status_message: None,
            result_available,
            cancellable,
            failure_code: None,
            failure_message: None,
            origin_conversation_id,
            origin_message_id,
            origin_tool_id,
            origin_tool_name,
            target_message_id,
            notification_status,
            notification_message_id: None,
            created_time,
            started_time: None,
            completed_time: None,
            last_update_time,
            tracking_status,
            tracking_failure_code: None,
            last_poll_error: None,
        }
    }
}
