/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AsyncTaskPage : AsyncTaskPage 的公开协议结构。 / Public contract for async task page.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AsyncTaskPage {
    /// 记录列表 / records。
    #[serde(rename = "records")]
    pub records: Vec<models::AsyncTask>,
    /// 分页信息 / page metadata。
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
}

impl AsyncTaskPage {
    /// AsyncTaskPage 的公开协议结构。 / Public contract for async task page.
    pub fn new(records: Vec<models::AsyncTask>, page: models::PageInfo) -> AsyncTaskPage {
        AsyncTaskPage {
            records,
            page: Box::new(page),
        }
    }
}
