/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AttachmentExtension : AttachmentExtension 的公开协议结构。 / Public contract for attachment extension.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachmentExtension {
    /// 字段 ext / ext field。
    #[serde(rename = "ext")]
    pub ext: String,
    /// 字段 media / media field。
    #[serde(rename = "media")]
    pub media: String,
}

impl AttachmentExtension {
    /// AttachmentExtension 的公开协议结构。 / Public contract for attachment extension.
    pub fn new(ext: String, media: String) -> AttachmentExtension {
        AttachmentExtension { ext, media }
    }
}
