/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChartTimeContext : ChartTimeContext 的公开协议结构。 / Public contract for chart time context.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChartTimeContext {
    /// 字段 asOfInstant / as of instant field。
    #[serde(rename = "asOfInstant")]
    pub as_of_instant: chrono::DateTime<chrono::FixedOffset>,
    /// 字段 tenantZoneId / tenant zone id field。
    #[serde(rename = "tenantZoneId")]
    pub tenant_zone_id: String,
}

impl ChartTimeContext {
    /// ChartTimeContext 的公开协议结构。 / Public contract for chart time context.
    pub fn new(
        as_of_instant: chrono::DateTime<chrono::FixedOffset>,
        tenant_zone_id: String,
    ) -> ChartTimeContext {
        ChartTimeContext {
            as_of_instant,
            tenant_zone_id,
        }
    }
}
