/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChartSpec : ChartSpec 的公开协议结构。 / Public contract for chart spec.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChartSpec {
    /// 字段 version / version field。
    #[serde(rename = "version")]
    pub version: i32,
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 标题 / title。
    #[serde(rename = "title")]
    pub title: String,
    /// 字段 subtitle / subtitle field。
    #[serde(
        rename = "subtitle",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subtitle: Option<Option<String>>,
    /// 字段 categoryColumn / category column field。
    #[serde(rename = "categoryColumn")]
    pub category_column: String,
    /// 字段 categoryType / category type field。
    #[serde(rename = "categoryType")]
    pub category_type: CategoryType,
    /// 字段 orientation / orientation field。
    #[serde(rename = "orientation")]
    pub orientation: Orientation,
    /// 字段 series / series field。
    #[serde(rename = "series")]
    pub series: Vec<models::ChartSeries>,
    /// 字段 legend / legend field。
    #[serde(rename = "legend")]
    pub legend: bool,
    /// 字段 dataZoom / data zoom field。
    #[serde(rename = "dataZoom")]
    pub data_zoom: DataZoom,
    /// 字段 nullPolicy / null policy field。
    #[serde(rename = "nullPolicy")]
    pub null_policy: NullPolicy,
}

impl ChartSpec {
    /// ChartSpec 的公开协议结构。 / Public contract for chart spec.
    pub fn new(
        version: i32,
        r#type: Type,
        title: String,
        category_column: String,
        category_type: CategoryType,
        orientation: Orientation,
        series: Vec<models::ChartSeries>,
        legend: bool,
        data_zoom: DataZoom,
        null_policy: NullPolicy,
    ) -> ChartSpec {
        ChartSpec {
            version,
            r#type,
            title,
            subtitle: None,
            category_column,
            category_type,
            orientation,
            series,
            legend,
            data_zoom,
            null_policy,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "BAR")]
    Bar,
    #[serde(rename = "LINE")]
    Line,
    #[serde(rename = "BAR_LINE")]
    BarLine,
    #[serde(rename = "STACKED_BAR")]
    StackedBar,
    #[serde(rename = "PIE")]
    Pie,
}

impl Default for Type {
    fn default() -> Type {
        Self::Bar
    }
}
/// 字段 categoryType / category type field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CategoryType {
    #[serde(rename = "CATEGORY")]
    Category,
    #[serde(rename = "TIME")]
    Time,
}

impl Default for CategoryType {
    fn default() -> CategoryType {
        Self::Category
    }
}
/// 字段 orientation / orientation field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Orientation {
    #[serde(rename = "VERTICAL")]
    Vertical,
    #[serde(rename = "HORIZONTAL")]
    Horizontal,
}

impl Default for Orientation {
    fn default() -> Orientation {
        Self::Vertical
    }
}
/// 字段 dataZoom / data zoom field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataZoom {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "AUTO")]
    Auto,
}

impl Default for DataZoom {
    fn default() -> DataZoom {
        Self::None
    }
}
/// 字段 nullPolicy / null policy field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NullPolicy {
    #[serde(rename = "GAP")]
    Gap,
    #[serde(rename = "ZERO")]
    Zero,
    #[serde(rename = "REJECT")]
    Reject,
}

impl Default for NullPolicy {
    fn default() -> NullPolicy {
        Self::Gap
    }
}
