/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChartColumnData : ChartColumnData 的公开协议结构。 / Public contract for chart column data.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ChartColumnData {
    #[serde(rename = "STRING")]
    String(Box<models::StringChartColumn>),
    #[serde(rename = "INTEGER")]
    Integer(Box<models::IntegerChartColumn>),
    #[serde(rename = "DECIMAL")]
    Decimal(Box<models::DecimalChartColumn>),
    #[serde(rename = "DOUBLE")]
    Double(Box<models::DoubleChartColumn>),
    #[serde(rename = "BOOLEAN")]
    Boolean(Box<models::BooleanChartColumn>),
    #[serde(rename = "LOCAL_DATE")]
    LocalDate(Box<models::LocalDateChartColumn>),
    #[serde(rename = "LOCAL_DATE_TIME")]
    LocalDateTime(Box<models::LocalDateTimeChartColumn>),
    #[serde(rename = "LOCAL_TIME")]
    LocalTime(Box<models::LocalTimeChartColumn>),
    #[serde(rename = "INSTANT")]
    Instant(Box<models::InstantChartColumn>),
}

impl Default for ChartColumnData {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
