/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChartSpec : ChartSpec 的公开协议结构。 / Public contract for chart spec.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChartSpec {
    /// 字段 version / version field。
    #[serde(rename = "version")]
    pub version: i32,
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 标题 / title。
    #[serde(rename = "title")]
    pub title: String,
    /// 字段 subtitle / subtitle field。
    #[serde(
        rename = "subtitle",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subtitle: Option<Option<String>>,
    /// 字段 categoryColumn / category column field。
    #[serde(rename = "categoryColumn")]
    pub category_column: String,
    /// 字段 categoryType / category type field。
    #[serde(rename = "categoryType")]
    pub category_type: CategoryType,
    /// 字段 orientation / orientation field。
    #[serde(rename = "orientation")]
    pub orientation: Orientation,
    /// 字段 series / series field。
    #[serde(rename = "series")]
    pub series: Vec<models::ChartSeries>,
    /// 字段 legend / legend field。
    #[serde(rename = "legend")]
    pub legend: bool,
    /// 字段 dataZoom / data zoom field。
    #[serde(rename = "dataZoom")]
    pub data_zoom: DataZoom,
    /// 字段 nullPolicy / null policy field。
    #[serde(rename = "nullPolicy")]
    pub null_policy: NullPolicy,
}

impl ChartSpec {
    /// ChartSpec 的公开协议结构。 / Public contract for chart spec.
    pub fn new(
        version: i32,
        r#type: Type,
        title: String,
        category_column: String,
        category_type: CategoryType,
        orientation: Orientation,
        series: Vec<models::ChartSeries>,
        legend: bool,
        data_zoom: DataZoom,
        null_policy: NullPolicy,
    ) -> ChartSpec {
        ChartSpec {
            version,
            r#type,
            title,
            subtitle: None,
            category_column,
            category_type,
            orientation,
            series,
            legend,
            data_zoom,
            null_policy,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "BAR")]
    Bar,
    #[serde(rename = "LINE")]
    Line,
    #[serde(rename = "BAR_LINE")]
    BarLine,
    #[serde(rename = "STACKED_BAR")]
    StackedBar,
    #[serde(rename = "PIE")]
    Pie,
}

impl Default for Type {
    fn default() -> Type {
        Self::Bar
    }
}
/// 字段 categoryType / category type field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CategoryType {
    #[serde(rename = "CATEGORY")]
    Category,
    #[serde(rename = "TIME")]
    Time,
}

impl Default for CategoryType {
    fn default() -> CategoryType {
        Self::Category
    }
}
/// 字段 orientation / orientation field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Orientation {
    #[serde(rename = "VERTICAL")]
    Vertical,
    #[serde(rename = "HORIZONTAL")]
    Horizontal,
}

impl Default for Orientation {
    fn default() -> Orientation {
        Self::Vertical
    }
}
/// 字段 dataZoom / data zoom field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataZoom {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "AUTO")]
    Auto,
}

impl Default for DataZoom {
    fn default() -> DataZoom {
        Self::None
    }
}
/// 字段 nullPolicy / null policy field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NullPolicy {
    #[serde(rename = "GAP")]
    Gap,
    #[serde(rename = "ZERO")]
    Zero,
    #[serde(rename = "REJECT")]
    Reject,
}

impl Default for NullPolicy {
    fn default() -> NullPolicy {
        Self::Gap
    }
}
