/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChartSeries : ChartSeries 的公开协议结构。 / Public contract for chart series.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChartSeries {
    /// 字段 name / name field。
    #[serde(rename = "name")]
    pub name: String,
    /// 字段 valueColumn / value column field。
    #[serde(rename = "valueColumn")]
    pub value_column: String,
    /// 字段 renderType / render type field。
    #[serde(rename = "renderType")]
    pub render_type: RenderType,
    /// 字段 axis / axis field。
    #[serde(rename = "axis")]
    pub axis: Axis,
    /// 字段 numberFormat / number format field。
    #[serde(rename = "numberFormat")]
    pub number_format: Box<models::ChartNumberFormat>,
    /// 字段 stack / stack field。
    #[serde(
        rename = "stack",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stack: Option<Option<String>>,
}

impl ChartSeries {
    /// ChartSeries 的公开协议结构。 / Public contract for chart series.
    pub fn new(
        name: String,
        value_column: String,
        render_type: RenderType,
        axis: Axis,
        number_format: models::ChartNumberFormat,
    ) -> ChartSeries {
        ChartSeries {
            name,
            value_column,
            render_type,
            axis,
            number_format: Box::new(number_format),
            stack: None,
        }
    }
}
/// 字段 renderType / render type field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RenderType {
    #[serde(rename = "BAR")]
    Bar,
    #[serde(rename = "LINE")]
    Line,
    #[serde(rename = "PIE")]
    Pie,
}

impl Default for RenderType {
    fn default() -> RenderType {
        Self::Bar
    }
}
/// 字段 axis / axis field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Axis {
    #[serde(rename = "PRIMARY")]
    Primary,
    #[serde(rename = "SECONDARY")]
    Secondary,
}

impl Default for Axis {
    fn default() -> Axis {
        Self::Primary
    }
}
