/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChartNumberFormat : ChartNumberFormat 的公开协议结构。 / Public contract for chart number format.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChartNumberFormat {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: String,
    /// 字段 currency / currency field。
    #[serde(
        rename = "currency",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub currency: Option<Option<String>>,
    /// 字段 decimalPlaces / decimal places field。
    #[serde(rename = "decimalPlaces")]
    pub decimal_places: i32,
    /// 字段 valueScale / value scale field。
    #[serde(
        rename = "valueScale",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub value_scale: Option<Option<String>>,
}

impl ChartNumberFormat {
    /// ChartNumberFormat 的公开协议结构。 / Public contract for chart number format.
    pub fn new(r#type: String, decimal_places: i32) -> ChartNumberFormat {
        ChartNumberFormat {
            r#type,
            currency: None,
            decimal_places,
            value_scale: None,
        }
    }
}
