/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChartSeries : ChartSeries 的公开协议结构。 / Public contract for chart series.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChartSeries {
    /// 字段 name / name field。
    #[serde(rename = "name")]
    pub name: String,
    /// 字段 valueColumn / value column field。
    #[serde(rename = "valueColumn")]
    pub value_column: String,
    /// 字段 renderType / render type field。
    #[serde(rename = "renderType")]
    pub render_type: RenderType,
    /// 字段 axis / axis field。
    #[serde(rename = "axis")]
    pub axis: Axis,
    /// 字段 numberFormat / number format field。
    #[serde(rename = "numberFormat")]
    pub number_format: Box<models::ChartNumberFormat>,
    /// 字段 stack / stack field。
    #[serde(
        rename = "stack",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stack: Option<Option<String>>,
}

impl ChartSeries {
    /// ChartSeries 的公开协议结构。 / Public contract for chart series.
    pub fn new(
        name: String,
        value_column: String,
        render_type: RenderType,
        axis: Axis,
        number_format: models::ChartNumberFormat,
    ) -> ChartSeries {
        ChartSeries {
            name,
            value_column,
            render_type,
            axis,
            number_format: Box::new(number_format),
            stack: None,
        }
    }
}
/// 字段 renderType / render type field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RenderType {
    #[serde(rename = "BAR")]
    Bar,
    #[serde(rename = "LINE")]
    Line,
    #[serde(rename = "PIE")]
    Pie,
}

impl Default for RenderType {
    fn default() -> RenderType {
        Self::Bar
    }
}
/// 字段 axis / axis field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Axis {
    #[serde(rename = "PRIMARY")]
    Primary,
    #[serde(rename = "SECONDARY")]
    Secondary,
}

impl Default for Axis {
    fn default() -> Axis {
        Self::Primary
    }
}
