/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChartQualitySummary : ChartQualitySummary 的公开协议结构。 / Public contract for chart quality summary.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChartQualitySummary {
    /// 字段 nullValueCount / null value count field。
    #[serde(rename = "nullValueCount")]
    pub null_value_count: i64,
    /// 字段 nullValueColumns / null value columns field。
    #[serde(rename = "nullValueColumns")]
    pub null_value_columns: Vec<String>,
    /// 字段 zeroFilledValueCount / zero filled value count field。
    #[serde(rename = "zeroFilledValueCount")]
    pub zero_filled_value_count: i64,
}

impl ChartQualitySummary {
    /// ChartQualitySummary 的公开协议结构。 / Public contract for chart quality summary.
    pub fn new(
        null_value_count: i64,
        null_value_columns: Vec<String>,
        zero_filled_value_count: i64,
    ) -> ChartQualitySummary {
        ChartQualitySummary {
            null_value_count,
            null_value_columns,
            zero_filled_value_count,
        }
    }
}
