/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatOptions : ChatOptions 的公开协议结构。 / Public contract for chat options.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatOptions {
    /// 字段 model / model field。
    #[serde(
        rename = "model",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub model: Option<Option<String>>,
    /// 字段 frequencyPenalty / frequency penalty field。
    #[serde(
        rename = "frequencyPenalty",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub frequency_penalty: Option<Option<f64>>,
    /// 字段 maxTokens / max tokens field。
    #[serde(
        rename = "maxTokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_tokens: Option<Option<i32>>,
    /// 字段 presencePenalty / presence penalty field。
    #[serde(
        rename = "presencePenalty",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub presence_penalty: Option<Option<f64>>,
    /// 字段 stopSequences / stop sequences field。
    #[serde(
        rename = "stopSequences",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stop_sequences: Option<Option<Vec<String>>>,
    /// 字段 temperature / temperature field。
    #[serde(
        rename = "temperature",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub temperature: Option<Option<f64>>,
    /// 字段 topP / top p field。
    #[serde(
        rename = "topP",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub top_p: Option<Option<f64>>,
}

impl ChatOptions {
    /// ChatOptions 的公开协议结构。 / Public contract for chat options.
    pub fn new() -> ChatOptions {
        ChatOptions {
            model: None,
            frequency_penalty: None,
            max_tokens: None,
            presence_penalty: None,
            stop_sequences: None,
            temperature: None,
            top_p: None,
        }
    }
}
