/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatStreamProbeInput : ChatStreamProbeInput 的公开协议结构。 / Public contract for chat stream probe input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatStreamProbeInput {
    /// 字段 probeId / probe id field。
    #[serde(rename = "probeId")]
    pub probe_id: String,
}

impl ChatStreamProbeInput {
    /// ChatStreamProbeInput 的公开协议结构。 / Public contract for chat stream probe input.
    pub fn new(probe_id: String) -> ChatStreamProbeInput {
        ChatStreamProbeInput { probe_id }
    }
}
