/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatModelConfig : ChatModelConfig 的公开协议结构。 / Public contract for chat model config.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatModelConfig {
    /// 字段 maker / maker field。
    #[serde(rename = "maker")]
    pub maker: String,
    /// 字段 modelName / model name field。
    #[serde(rename = "modelName")]
    pub model_name: String,
    /// 字段 modelLabel / model label field。
    #[serde(rename = "modelLabel")]
    pub model_label: String,
    /// 字段 modelDescription / model description field。
    #[serde(rename = "modelDescription")]
    pub model_description: String,
    /// 字段 maxContextTokens / max context tokens field。
    #[serde(rename = "maxContextTokens")]
    pub max_context_tokens: i32,
    /// 字段 maxOutputTokens / max output tokens field。
    #[serde(rename = "maxOutputTokens")]
    pub max_output_tokens: i32,
    /// 字段 supportImage / support image field。
    #[serde(rename = "supportImage")]
    pub support_image: bool,
    /// 字段 supportVideo / support video field。
    #[serde(rename = "supportVideo")]
    pub support_video: bool,
    /// 字段 thinkingMode / thinking mode field。
    #[serde(rename = "thinkingMode")]
    pub thinking_mode: bool,
}

impl ChatModelConfig {
    /// ChatModelConfig 的公开协议结构。 / Public contract for chat model config.
    pub fn new(
        maker: String,
        model_name: String,
        model_label: String,
        model_description: String,
        max_context_tokens: i32,
        max_output_tokens: i32,
        support_image: bool,
        support_video: bool,
        thinking_mode: bool,
    ) -> ChatModelConfig {
        ChatModelConfig {
            maker,
            model_name,
            model_label,
            model_description,
            max_context_tokens,
            max_output_tokens,
            support_image,
            support_video,
            thinking_mode,
        }
    }
}
