/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatStreamProbeEvent : ChatStreamProbeEvent 的公开协议结构。 / Public contract for chat stream probe event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatStreamProbeEvent {
    /// 字段 probeId / probe id field。
    #[serde(rename = "probeId")]
    pub probe_id: String,
    /// 字段 sequence / sequence field。
    #[serde(rename = "sequence")]
    pub sequence: i32,
    /// 字段 serverElapsedMs / server elapsed ms field。
    #[serde(rename = "serverElapsedMs")]
    pub server_elapsed_ms: i64,
}

impl ChatStreamProbeEvent {
    /// ChatStreamProbeEvent 的公开协议结构。 / Public contract for chat stream probe event.
    pub fn new(probe_id: String, sequence: i32, server_elapsed_ms: i64) -> ChatStreamProbeEvent {
        ChatStreamProbeEvent {
            probe_id,
            sequence,
            server_elapsed_ms,
        }
    }
}
