/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatMessage : ChatMessage 的公开协议结构。 / Public contract for chat message.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ChatMessage {
    #[serde(rename = "SYSTEM")]
    System(Box<models::SystemChatMessage>),
    #[serde(rename = "USER")]
    User(Box<models::UserChatMessage>),
    #[serde(rename = "ASSISTANT")]
    Assistant(Box<models::AssistantChatMessage>),
    #[serde(rename = "TOOL")]
    Tool(Box<models::ToolResponseChatMessage>),
}

impl Default for ChatMessage {
    fn default() -> Self {
        Self::System(Default::default())
    }
}
