/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatModelConfig : ChatModelConfig 的公开协议结构。 / Public contract for chat model config.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatModelConfig {
    /// 字段 maker / maker field。
    #[serde(rename = "maker")]
    pub maker: String,
    /// 字段 modelName / model name field。
    #[serde(rename = "modelName")]
    pub model_name: String,
    /// 字段 modelLabel / model label field。
    #[serde(rename = "modelLabel")]
    pub model_label: String,
    /// 字段 modelDescription / model description field。
    #[serde(rename = "modelDescription")]
    pub model_description: String,
    /// 字段 maxContextTokens / max context tokens field。
    #[serde(rename = "maxContextTokens")]
    pub max_context_tokens: i32,
    /// 字段 maxOutputTokens / max output tokens field。
    #[serde(rename = "maxOutputTokens")]
    pub max_output_tokens: i32,
    /// 字段 supportImage / support image field。
    #[serde(rename = "supportImage")]
    pub support_image: bool,
    /// 字段 supportVideo / support video field。
    #[serde(rename = "supportVideo")]
    pub support_video: bool,
    /// 字段 thinkingMode / thinking mode field。
    #[serde(rename = "thinkingMode")]
    pub thinking_mode: bool,
}

impl ChatModelConfig {
    /// ChatModelConfig 的公开协议结构。 / Public contract for chat model config.
    pub fn new(
        maker: String,
        model_name: String,
        model_label: String,
        model_description: String,
        max_context_tokens: i32,
        max_output_tokens: i32,
        support_image: bool,
        support_video: bool,
        thinking_mode: bool,
    ) -> ChatModelConfig {
        ChatModelConfig {
            maker,
            model_name,
            model_label,
            model_description,
            max_context_tokens,
            max_output_tokens,
            support_image,
            support_video,
            thinking_mode,
        }
    }
}
