/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatModelSpec : ChatModelSpec 的公开协议结构。 / Public contract for chat model spec.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatModelSpec {
    /// 字段 keyGroupId / key group id field。
    #[serde(rename = "keyGroupId")]
    pub key_group_id: i64,
    /// 字段 model / model field。
    #[serde(rename = "model")]
    pub model: String,
    /// 字段 thinking / thinking field。
    #[serde(
        rename = "thinking",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub thinking: Option<Option<bool>>,
    /// 字段 stopSequences / stop sequences field。
    #[serde(
        rename = "stopSequences",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stop_sequences: Option<Option<Vec<String>>>,
    /// 字段 temperature / temperature field。
    #[serde(
        rename = "temperature",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub temperature: Option<Option<f64>>,
    /// 字段 maxTokens / max tokens field。
    #[serde(
        rename = "maxTokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_tokens: Option<Option<i32>>,
    /// 字段 topP / top p field。
    #[serde(
        rename = "topP",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub top_p: Option<Option<f64>>,
    /// 字段 topK / top k field。
    #[serde(
        rename = "topK",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub top_k: Option<Option<i32>>,
    /// 字段 frequencyPenalty / frequency penalty field。
    #[serde(
        rename = "frequencyPenalty",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub frequency_penalty: Option<Option<f64>>,
    /// 字段 presencePenalty / presence penalty field。
    #[serde(
        rename = "presencePenalty",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub presence_penalty: Option<Option<f64>>,
}

impl ChatModelSpec {
    /// ChatModelSpec 的公开协议结构。 / Public contract for chat model spec.
    pub fn new(key_group_id: i64, model: String) -> ChatModelSpec {
        ChatModelSpec {
            key_group_id,
            model,
            thinking: None,
            stop_sequences: None,
            temperature: None,
            max_tokens: None,
            top_p: None,
            top_k: None,
            frequency_penalty: None,
            presence_penalty: None,
        }
    }
}
