/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatModelSpec : ChatModelSpec 的公开协议结构。 / Public contract for chat model spec.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatModelSpec {
    /// 字段 keyGroupId / key group id field。
    #[serde(rename = "keyGroupId")]
    pub key_group_id: i64,
    /// 字段 model / model field。
    #[serde(rename = "model")]
    pub model: String,
    /// 字段 thinking / thinking field。
    #[serde(
        rename = "thinking",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub thinking: Option<Option<bool>>,
    /// 字段 stopSequences / stop sequences field。
    #[serde(
        rename = "stopSequences",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stop_sequences: Option<Option<Vec<String>>>,
    /// 字段 temperature / temperature field。
    #[serde(
        rename = "temperature",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub temperature: Option<Option<f64>>,
    /// 字段 maxTokens / max tokens field。
    #[serde(
        rename = "maxTokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_tokens: Option<Option<i32>>,
    /// 字段 topP / top p field。
    #[serde(
        rename = "topP",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub top_p: Option<Option<f64>>,
    /// 字段 topK / top k field。
    #[serde(
        rename = "topK",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub top_k: Option<Option<i32>>,
    /// 字段 frequencyPenalty / frequency penalty field。
    #[serde(
        rename = "frequencyPenalty",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub frequency_penalty: Option<Option<f64>>,
    /// 字段 presencePenalty / presence penalty field。
    #[serde(
        rename = "presencePenalty",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub presence_penalty: Option<Option<f64>>,
}

impl ChatModelSpec {
    /// ChatModelSpec 的公开协议结构。 / Public contract for chat model spec.
    pub fn new(key_group_id: i64, model: String) -> ChatModelSpec {
        ChatModelSpec {
            key_group_id,
            model,
            thinking: None,
            stop_sequences: None,
            temperature: None,
            max_tokens: None,
            top_p: None,
            top_k: None,
            frequency_penalty: None,
            presence_penalty: None,
        }
    }
}
