/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CitationMetadata : CitationMetadata 的公开协议结构。 / Public contract for citation metadata.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CitationMetadata {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: String,
    /// 字段 referenceId / reference id field。
    #[serde(rename = "referenceId")]
    pub reference_id: i64,
    /// 标题 / title。
    #[serde(
        rename = "title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<Option<String>>,
    /// 可读说明 / human-readable description。
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
}

impl CitationMetadata {
    /// CitationMetadata 的公开协议结构。 / Public contract for citation metadata.
    pub fn new(r#type: String, reference_id: i64) -> CitationMetadata {
        CitationMetadata {
            r#type,
            reference_id,
            title: None,
            description: None,
        }
    }
}
