/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CodeMessage : CodeMessage 的公开协议结构。 / Public contract for code message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeMessage {
    /// 字段 code / code field。
    #[serde(rename = "code")]
    pub code: String,
    /// 消息正文 / message text。
    #[serde(rename = "message")]
    pub message: String,
}

impl CodeMessage {
    /// CodeMessage 的公开协议结构。 / Public contract for code message.
    pub fn new(code: String, message: String) -> CodeMessage {
        CodeMessage { code, message }
    }
}
