/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfirmUploadInput : ConfirmUploadInput 的公开协议结构。 / Public contract for confirm upload input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfirmUploadInput {
    /// 字段 fileUk / file uk field。
    #[serde(rename = "fileUk")]
    pub file_uk: String,
    /// 字段 contentMd5 / content md5 field。
    #[serde(rename = "contentMd5")]
    pub content_md5: String,
}

impl ConfirmUploadInput {
    /// ConfirmUploadInput 的公开协议结构。 / Public contract for confirm upload input.
    pub fn new(file_uk: String, content_md5: String) -> ConfirmUploadInput {
        ConfirmUploadInput {
            file_uk,
            content_md5,
        }
    }
}
