/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationSummary : ConversationSummary 的公开协议结构。 / Public contract for conversation summary.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationSummary {
    /// 会话 ID / conversation ID。
    #[serde(rename = "conversationId")]
    pub conversation_id: String,
    /// 字段 conversationType / conversation type field。
    #[serde(rename = "conversationType")]
    pub conversation_type: String,
    /// 标题 / title。
    #[serde(
        rename = "title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<Option<String>>,
    /// 字段 titleState / title state field。
    #[serde(rename = "titleState")]
    pub title_state: String,
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
    /// 字段 messageCount / message count field。
    #[serde(rename = "messageCount")]
    pub message_count: i64,
    /// 总 Token 数 / total token count。
    #[serde(rename = "totalTokens")]
    pub total_tokens: i64,
    /// 字段 totalInputTokens / total input tokens field。
    #[serde(rename = "totalInputTokens")]
    pub total_input_tokens: i64,
    /// 字段 totalOutputTokens / total output tokens field。
    #[serde(rename = "totalOutputTokens")]
    pub total_output_tokens: i64,
    /// 字段 usage / usage field。
    #[serde(rename = "usage")]
    pub usage: Box<models::Usage>,
    /// 创建时间 / creation time。
    #[serde(rename = "createdTime")]
    pub created_time: chrono::DateTime<chrono::FixedOffset>,
    /// 最后更新时间 / last update time。
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
}

impl ConversationSummary {
    /// ConversationSummary 的公开协议结构。 / Public contract for conversation summary.
    pub fn new(
        conversation_id: String,
        conversation_type: String,
        title_state: String,
        status: String,
        message_count: i64,
        total_tokens: i64,
        total_input_tokens: i64,
        total_output_tokens: i64,
        usage: models::Usage,
        created_time: chrono::DateTime<chrono::FixedOffset>,
        last_update_time: chrono::DateTime<chrono::FixedOffset>,
    ) -> ConversationSummary {
        ConversationSummary {
            conversation_id,
            conversation_type,
            title: None,
            title_state,
            status,
            message_count,
            total_tokens,
            total_input_tokens,
            total_output_tokens,
            usage: Box::new(usage),
            created_time,
            last_update_time,
        }
    }
}
