/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationIds : ConversationIds 的公开协议结构。 / Public contract for conversation ids.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationIds {
    /// 字段 conversationIds / conversation ids field。
    #[serde(rename = "conversationIds")]
    pub conversation_ids: Vec<String>,
}

impl ConversationIds {
    /// ConversationIds 的公开协议结构。 / Public contract for conversation ids.
    pub fn new(conversation_ids: Vec<String>) -> ConversationIds {
        ConversationIds { conversation_ids }
    }
}
