/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationMessage : ConversationMessage 的公开协议结构。 / Public contract for conversation message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationMessage {
    /// 消息 ID / message ID。
    #[serde(rename = "messageId")]
    pub message_id: String,
    /// 字段 userMessage / user message field。
    #[serde(rename = "userMessage")]
    pub user_message: Box<models::ConversationUserMessage>,
    /// 输入 Token 数 / input token count。
    #[serde(rename = "inputTokens")]
    pub input_tokens: i64,
    /// 输出 Token 数 / output token count。
    #[serde(rename = "outputTokens")]
    pub output_tokens: i64,
    /// 总 Token 数 / total token count。
    #[serde(rename = "totalTokens")]
    pub total_tokens: i64,
    /// 字段 usage / usage field。
    #[serde(rename = "usage")]
    pub usage: Box<models::Usage>,
    /// 字段 executionTimeMillis / execution time millis field。
    #[serde(rename = "executionTimeMillis")]
    pub execution_time_millis: i64,
    /// 字段 processingSteps / processing steps field。
    #[serde(rename = "processingSteps")]
    pub processing_steps: i32,
    /// 字段 totalToolCalls / total tool calls field。
    #[serde(rename = "totalToolCalls")]
    pub total_tool_calls: i32,
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
    /// 创建时间 / creation time。
    #[serde(rename = "createdTime")]
    pub created_time: chrono::DateTime<chrono::FixedOffset>,
    /// 最后更新时间 / last update time。
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
    /// 字段 executionType / execution type field。
    #[serde(rename = "executionType")]
    pub execution_type: String,
    /// 字段 parentMessageId / parent message id field。
    #[serde(
        rename = "parentMessageId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_message_id: Option<Option<String>>,
}

impl ConversationMessage {
    /// ConversationMessage 的公开协议结构。 / Public contract for conversation message.
    pub fn new(
        message_id: String,
        user_message: models::ConversationUserMessage,
        input_tokens: i64,
        output_tokens: i64,
        total_tokens: i64,
        usage: models::Usage,
        execution_time_millis: i64,
        processing_steps: i32,
        total_tool_calls: i32,
        status: String,
        created_time: chrono::DateTime<chrono::FixedOffset>,
        last_update_time: chrono::DateTime<chrono::FixedOffset>,
        execution_type: String,
    ) -> ConversationMessage {
        ConversationMessage {
            message_id,
            user_message: Box::new(user_message),
            input_tokens,
            output_tokens,
            total_tokens,
            usage: Box::new(usage),
            execution_time_millis,
            processing_steps,
            total_tool_calls,
            status,
            created_time,
            last_update_time,
            execution_type,
            parent_message_id: None,
        }
    }
}
