/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationContextUsage : ConversationContextUsage 的公开协议结构。 / Public contract for conversation context usage.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationContextUsage {
    /// 字段 systemPromptTokens / system prompt tokens field。
    #[serde(rename = "systemPromptTokens")]
    pub system_prompt_tokens: i32,
    /// 字段 sessionMessageTokens / session message tokens field。
    #[serde(rename = "sessionMessageTokens")]
    pub session_message_tokens: i32,
    /// 字段 maxContextTokens / max context tokens field。
    #[serde(rename = "maxContextTokens")]
    pub max_context_tokens: i32,
    /// 字段 toolDefinitionTokens / tool definition tokens field。
    #[serde(rename = "toolDefinitionTokens")]
    pub tool_definition_tokens: i32,
    /// 字段 protocolReserveTokens / protocol reserve tokens field。
    #[serde(rename = "protocolReserveTokens")]
    pub protocol_reserve_tokens: i32,
    /// 字段 activeContextTokens / active context tokens field。
    #[serde(rename = "activeContextTokens")]
    pub active_context_tokens: i64,
    /// 字段 requestedOutputTokens / requested output tokens field。
    #[serde(rename = "requestedOutputTokens")]
    pub requested_output_tokens: i32,
    /// 字段 messageAssemblyReserveTokens / message assembly reserve tokens field。
    #[serde(rename = "messageAssemblyReserveTokens")]
    pub message_assembly_reserve_tokens: i32,
    /// 字段 requiredContextTokens / required context tokens field。
    #[serde(rename = "requiredContextTokens")]
    pub required_context_tokens: i64,
    /// 字段 activeUsageRatio / active usage ratio field。
    #[serde(
        rename = "activeUsageRatio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub active_usage_ratio: Option<Option<f64>>,
    /// 字段 requiredUsageRatio / required usage ratio field。
    #[serde(
        rename = "requiredUsageRatio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub required_usage_ratio: Option<Option<f64>>,
    /// 字段 calculationSource / calculation source field。
    #[serde(rename = "calculationSource")]
    pub calculation_source: String,
}

impl ConversationContextUsage {
    /// ConversationContextUsage 的公开协议结构。 / Public contract for conversation context usage.
    pub fn new(
        system_prompt_tokens: i32,
        session_message_tokens: i32,
        max_context_tokens: i32,
        tool_definition_tokens: i32,
        protocol_reserve_tokens: i32,
        active_context_tokens: i64,
        requested_output_tokens: i32,
        message_assembly_reserve_tokens: i32,
        required_context_tokens: i64,
        calculation_source: String,
    ) -> ConversationContextUsage {
        ConversationContextUsage {
            system_prompt_tokens,
            session_message_tokens,
            max_context_tokens,
            tool_definition_tokens,
            protocol_reserve_tokens,
            active_context_tokens,
            requested_output_tokens,
            message_assembly_reserve_tokens,
            required_context_tokens,
            active_usage_ratio: None,
            required_usage_ratio: None,
            calculation_source,
        }
    }
}
