/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationShareRevoked : ConversationShareRevoked 的公开协议结构。 / Public contract for conversation share revoked.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationShareRevoked {
    /// 字段 shareId / share id field。
    #[serde(rename = "shareId")]
    pub share_id: i64,
}

impl ConversationShareRevoked {
    /// ConversationShareRevoked 的公开协议结构。 / Public contract for conversation share revoked.
    pub fn new(share_id: i64) -> ConversationShareRevoked {
        ConversationShareRevoked { share_id }
    }
}
