/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationShareInput : ConversationShareInput 的公开协议结构。 / Public contract for conversation share input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationShareInput {
    /// 字段 password / password field。
    #[serde(
        rename = "password",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub password: Option<Option<String>>,
    /// 字段 expiresAt / expires at field。
    #[serde(
        rename = "expiresAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl ConversationShareInput {
    /// ConversationShareInput 的公开协议结构。 / Public contract for conversation share input.
    pub fn new() -> ConversationShareInput {
        ConversationShareInput {
            password: None,
            expires_at: None,
        }
    }
}
