/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationTitle : ConversationTitle 的公开协议结构。 / Public contract for conversation title.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationTitle {
    /// 会话 ID / conversation ID。
    #[serde(rename = "conversationId")]
    pub conversation_id: String,
    /// 标题 / title。
    #[serde(
        rename = "title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<Option<String>>,
    /// 字段 titleState / title state field。
    #[serde(rename = "titleState")]
    pub title_state: String,
}

impl ConversationTitle {
    /// ConversationTitle 的公开协议结构。 / Public contract for conversation title.
    pub fn new(conversation_id: String, title_state: String) -> ConversationTitle {
        ConversationTitle {
            conversation_id,
            title: None,
            title_state,
        }
    }
}
