/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationMessage : ConversationMessage 的公开协议结构。 / Public contract for conversation message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationMessage {
    /// 消息 ID / message ID。
    #[serde(rename = "messageId")]
    pub message_id: String,
    /// 字段 userMessage / user message field。
    #[serde(rename = "userMessage")]
    pub user_message: Box<models::ConversationUserMessage>,
    /// 输入 Token 数 / input token count。
    #[serde(rename = "inputTokens")]
    pub input_tokens: i64,
    /// 输出 Token 数 / output token count。
    #[serde(rename = "outputTokens")]
    pub output_tokens: i64,
    /// 总 Token 数 / total token count。
    #[serde(rename = "totalTokens")]
    pub total_tokens: i64,
    /// 字段 usage / usage field。
    #[serde(rename = "usage")]
    pub usage: Box<models::Usage>,
    /// 字段 executionTimeMillis / execution time millis field。
    #[serde(rename = "executionTimeMillis")]
    pub execution_time_millis: i64,
    /// 字段 processingSteps / processing steps field。
    #[serde(rename = "processingSteps")]
    pub processing_steps: i32,
    /// 字段 totalToolCalls / total tool calls field。
    #[serde(rename = "totalToolCalls")]
    pub total_tool_calls: i32,
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
    /// 创建时间 / creation time。
    #[serde(rename = "createdTime")]
    pub created_time: chrono::DateTime<chrono::FixedOffset>,
    /// 最后更新时间 / last update time。
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
    /// 字段 executionType / execution type field。
    #[serde(rename = "executionType")]
    pub execution_type: String,
    /// 字段 parentMessageId / parent message id field。
    #[serde(
        rename = "parentMessageId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_message_id: Option<Option<String>>,
}

impl ConversationMessage {
    /// ConversationMessage 的公开协议结构。 / Public contract for conversation message.
    pub fn new(
        message_id: String,
        user_message: models::ConversationUserMessage,
        input_tokens: i64,
        output_tokens: i64,
        total_tokens: i64,
        usage: models::Usage,
        execution_time_millis: i64,
        processing_steps: i32,
        total_tool_calls: i32,
        status: String,
        created_time: chrono::DateTime<chrono::FixedOffset>,
        last_update_time: chrono::DateTime<chrono::FixedOffset>,
        execution_type: String,
    ) -> ConversationMessage {
        ConversationMessage {
            message_id,
            user_message: Box::new(user_message),
            input_tokens,
            output_tokens,
            total_tokens,
            usage: Box::new(usage),
            execution_time_millis,
            processing_steps,
            total_tool_calls,
            status,
            created_time,
            last_update_time,
            execution_type,
            parent_message_id: None,
        }
    }
}
