/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationConfig : ConversationConfig 的公开协议结构。 / Public contract for conversation config.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationConfig {
    /// 字段 lastChatModelSpec / last chat model spec field。
    #[serde(
        rename = "lastChatModelSpec",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_chat_model_spec: Option<Option<Box<models::ChatModelSpec>>>,
}

impl ConversationConfig {
    /// ConversationConfig 的公开协议结构。 / Public contract for conversation config.
    pub fn new() -> ConversationConfig {
        ConversationConfig {
            last_chat_model_spec: None,
        }
    }
}
