/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationReadReceiptInput : ConversationReadReceiptInput 的公开协议结构。 / Public contract for conversation read receipt input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationReadReceiptInput {
    /// 消息 ID / message ID。
    #[serde(rename = "messageId")]
    pub message_id: String,
}

impl ConversationReadReceiptInput {
    /// ConversationReadReceiptInput 的公开协议结构。 / Public contract for conversation read receipt input.
    pub fn new(message_id: String) -> ConversationReadReceiptInput {
        ConversationReadReceiptInput { message_id }
    }
}
