/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationContextUsage : ConversationContextUsage 的公开协议结构。 / Public contract for conversation context usage.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationContextUsage {
    /// 字段 systemPromptTokens / system prompt tokens field。
    #[serde(rename = "systemPromptTokens")]
    pub system_prompt_tokens: i32,
    /// 字段 sessionMessageTokens / session message tokens field。
    #[serde(rename = "sessionMessageTokens")]
    pub session_message_tokens: i32,
    /// 字段 maxContextTokens / max context tokens field。
    #[serde(rename = "maxContextTokens")]
    pub max_context_tokens: i32,
    /// 字段 toolDefinitionTokens / tool definition tokens field。
    #[serde(rename = "toolDefinitionTokens")]
    pub tool_definition_tokens: i32,
    /// 字段 protocolReserveTokens / protocol reserve tokens field。
    #[serde(rename = "protocolReserveTokens")]
    pub protocol_reserve_tokens: i32,
    /// 字段 activeContextTokens / active context tokens field。
    #[serde(rename = "activeContextTokens")]
    pub active_context_tokens: i64,
    /// 字段 requestedOutputTokens / requested output tokens field。
    #[serde(rename = "requestedOutputTokens")]
    pub requested_output_tokens: i32,
    /// 字段 messageAssemblyReserveTokens / message assembly reserve tokens field。
    #[serde(rename = "messageAssemblyReserveTokens")]
    pub message_assembly_reserve_tokens: i32,
    /// 字段 requiredContextTokens / required context tokens field。
    #[serde(rename = "requiredContextTokens")]
    pub required_context_tokens: i64,
    /// 字段 activeUsageRatio / active usage ratio field。
    #[serde(
        rename = "activeUsageRatio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub active_usage_ratio: Option<Option<f64>>,
    /// 字段 requiredUsageRatio / required usage ratio field。
    #[serde(
        rename = "requiredUsageRatio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub required_usage_ratio: Option<Option<f64>>,
    /// 字段 calculationSource / calculation source field。
    #[serde(rename = "calculationSource")]
    pub calculation_source: String,
}

impl ConversationContextUsage {
    /// ConversationContextUsage 的公开协议结构。 / Public contract for conversation context usage.
    pub fn new(
        system_prompt_tokens: i32,
        session_message_tokens: i32,
        max_context_tokens: i32,
        tool_definition_tokens: i32,
        protocol_reserve_tokens: i32,
        active_context_tokens: i64,
        requested_output_tokens: i32,
        message_assembly_reserve_tokens: i32,
        required_context_tokens: i64,
        calculation_source: String,
    ) -> ConversationContextUsage {
        ConversationContextUsage {
            system_prompt_tokens,
            session_message_tokens,
            max_context_tokens,
            tool_definition_tokens,
            protocol_reserve_tokens,
            active_context_tokens,
            requested_output_tokens,
            message_assembly_reserve_tokens,
            required_context_tokens,
            active_usage_ratio: None,
            required_usage_ratio: None,
            calculation_source,
        }
    }
}
