/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationStats : ConversationStats 的公开协议结构。 / Public contract for conversation stats.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationStats {
    /// 字段 publishId / publish id field。
    #[serde(rename = "publishId")]
    pub publish_id: String,
    /// 字段 totalConversations / total conversations field。
    #[serde(rename = "totalConversations")]
    pub total_conversations: i64,
    /// 字段 activeConversations / active conversations field。
    #[serde(rename = "activeConversations")]
    pub active_conversations: i64,
    /// 字段 totalMessages / total messages field。
    #[serde(rename = "totalMessages")]
    pub total_messages: i64,
    /// 总 Token 数 / total token count。
    #[serde(rename = "totalTokens")]
    pub total_tokens: i64,
    /// 字段 avgMessagesPerConversation / avg messages per conversation field。
    #[serde(rename = "avgMessagesPerConversation")]
    pub avg_messages_per_conversation: f64,
}

impl ConversationStats {
    /// ConversationStats 的公开协议结构。 / Public contract for conversation stats.
    pub fn new(
        publish_id: String,
        total_conversations: i64,
        active_conversations: i64,
        total_messages: i64,
        total_tokens: i64,
        avg_messages_per_conversation: f64,
    ) -> ConversationStats {
        ConversationStats {
            publish_id,
            total_conversations,
            active_conversations,
            total_messages,
            total_tokens,
            avg_messages_per_conversation,
        }
    }
}
