/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationShareRecord : ConversationShareRecord 的公开协议结构。 / Public contract for conversation share record.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationShareRecord {
    /// 字段 shareId / share id field。
    #[serde(rename = "shareId")]
    pub share_id: i64,
    /// 字段 shareCode / share code field。
    #[serde(rename = "shareCode")]
    pub share_code: String,
    /// 字段 serverName / server name field。
    #[serde(rename = "serverName")]
    pub server_name: String,
    /// 字段 accessMode / access mode field。
    #[serde(rename = "accessMode")]
    pub access_mode: String,
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
    /// 字段 expiresAt / expires at field。
    #[serde(
        rename = "expiresAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// 创建时间 / creation time。
    #[serde(rename = "createdTime")]
    pub created_time: chrono::DateTime<chrono::FixedOffset>,
    /// 最后更新时间 / last update time。
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
}

impl ConversationShareRecord {
    /// ConversationShareRecord 的公开协议结构。 / Public contract for conversation share record.
    pub fn new(
        share_id: i64,
        share_code: String,
        server_name: String,
        access_mode: String,
        status: String,
        created_time: chrono::DateTime<chrono::FixedOffset>,
        last_update_time: chrono::DateTime<chrono::FixedOffset>,
    ) -> ConversationShareRecord {
        ConversationShareRecord {
            share_id,
            share_code,
            server_name,
            access_mode,
            status,
            expires_at: None,
            created_time,
            last_update_time,
        }
    }
}
