/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationStatusInput : ConversationStatusInput 的公开协议结构。 / Public contract for conversation status input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationStatusInput {
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
}

impl ConversationStatusInput {
    /// ConversationStatusInput 的公开协议结构。 / Public contract for conversation status input.
    pub fn new(status: String) -> ConversationStatusInput {
        ConversationStatusInput { status }
    }
}
