/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationActivityList : ConversationActivityList 的公开协议结构。 / Public contract for conversation activity list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationActivityList {
    /// 记录列表 / records。
    #[serde(rename = "records")]
    pub records: Vec<models::ConversationActivity>,
}

impl ConversationActivityList {
    /// ConversationActivityList 的公开协议结构。 / Public contract for conversation activity list.
    pub fn new(records: Vec<models::ConversationActivity>) -> ConversationActivityList {
        ConversationActivityList { records }
    }
}
