/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationSummaryList : ConversationSummaryList 的公开协议结构。 / Public contract for conversation summary list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationSummaryList {
    /// 记录列表 / records。
    #[serde(rename = "records")]
    pub records: Vec<models::ConversationSummary>,
}

impl ConversationSummaryList {
    /// ConversationSummaryList 的公开协议结构。 / Public contract for conversation summary list.
    pub fn new(records: Vec<models::ConversationSummary>) -> ConversationSummaryList {
        ConversationSummaryList { records }
    }
}
