/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationSummary : ConversationSummary 的公开协议结构。 / Public contract for conversation summary.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationSummary {
    /// 会话 ID / conversation ID。
    #[serde(rename = "conversationId")]
    pub conversation_id: String,
    /// 字段 conversationType / conversation type field。
    #[serde(rename = "conversationType")]
    pub conversation_type: String,
    /// 标题 / title。
    #[serde(
        rename = "title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<Option<String>>,
    /// 字段 titleState / title state field。
    #[serde(rename = "titleState")]
    pub title_state: String,
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
    /// 字段 messageCount / message count field。
    #[serde(rename = "messageCount")]
    pub message_count: i64,
    /// 总 Token 数 / total token count。
    #[serde(rename = "totalTokens")]
    pub total_tokens: i64,
    /// 字段 totalInputTokens / total input tokens field。
    #[serde(rename = "totalInputTokens")]
    pub total_input_tokens: i64,
    /// 字段 totalOutputTokens / total output tokens field。
    #[serde(rename = "totalOutputTokens")]
    pub total_output_tokens: i64,
    /// 字段 usage / usage field。
    #[serde(rename = "usage")]
    pub usage: Box<models::Usage>,
    /// 创建时间 / creation time。
    #[serde(rename = "createdTime")]
    pub created_time: chrono::DateTime<chrono::FixedOffset>,
    /// 最后更新时间 / last update time。
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
}

impl ConversationSummary {
    /// ConversationSummary 的公开协议结构。 / Public contract for conversation summary.
    pub fn new(
        conversation_id: String,
        conversation_type: String,
        title_state: String,
        status: String,
        message_count: i64,
        total_tokens: i64,
        total_input_tokens: i64,
        total_output_tokens: i64,
        usage: models::Usage,
        created_time: chrono::DateTime<chrono::FixedOffset>,
        last_update_time: chrono::DateTime<chrono::FixedOffset>,
    ) -> ConversationSummary {
        ConversationSummary {
            conversation_id,
            conversation_type,
            title: None,
            title_state,
            status,
            message_count,
            total_tokens,
            total_input_tokens,
            total_output_tokens,
            usage: Box::new(usage),
            created_time,
            last_update_time,
        }
    }
}
