/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationReadReceipt : ConversationReadReceipt 的公开协议结构。 / Public contract for conversation read receipt.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationReadReceipt {
    /// 会话 ID / conversation ID。
    #[serde(rename = "conversationId")]
    pub conversation_id: String,
    /// 字段 executionStatus / execution status field。
    #[serde(rename = "executionStatus")]
    pub execution_status: String,
    /// 字段 activeMessageId / active message id field。
    #[serde(
        rename = "activeMessageId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub active_message_id: Option<Option<String>>,
    /// 字段 executionEpoch / execution epoch field。
    #[serde(
        rename = "executionEpoch",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub execution_epoch: Option<Option<String>>,
    /// 字段 executionStartedTime / execution started time field。
    #[serde(
        rename = "executionStartedTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub execution_started_time: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// 字段 latestTerminalMessageId / latest terminal message id field。
    #[serde(
        rename = "latestTerminalMessageId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub latest_terminal_message_id: Option<Option<String>>,
    /// 字段 latestTerminalTime / latest terminal time field。
    #[serde(
        rename = "latestTerminalTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub latest_terminal_time: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// 字段 hasUnreadCompletion / has unread completion field。
    #[serde(rename = "hasUnreadCompletion")]
    pub has_unread_completion: bool,
}

impl ConversationReadReceipt {
    /// ConversationReadReceipt 的公开协议结构。 / Public contract for conversation read receipt.
    pub fn new(
        conversation_id: String,
        execution_status: String,
        has_unread_completion: bool,
    ) -> ConversationReadReceipt {
        ConversationReadReceipt {
            conversation_id,
            execution_status,
            active_message_id: None,
            execution_epoch: None,
            execution_started_time: None,
            latest_terminal_message_id: None,
            latest_terminal_time: None,
            has_unread_completion,
        }
    }
}
