/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConversationShareCreated : ConversationShareCreated 的公开协议结构。 / Public contract for conversation share created.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationShareCreated {
    /// 字段 shareId / share id field。
    #[serde(rename = "shareId")]
    pub share_id: i64,
    /// 字段 shareCode / share code field。
    #[serde(rename = "shareCode")]
    pub share_code: String,
    /// 字段 serverName / server name field。
    #[serde(rename = "serverName")]
    pub server_name: String,
    /// 字段 passwordRequired / password required field。
    #[serde(rename = "passwordRequired")]
    pub password_required: bool,
    /// 字段 expiresAt / expires at field。
    #[serde(
        rename = "expiresAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl ConversationShareCreated {
    /// ConversationShareCreated 的公开协议结构。 / Public contract for conversation share created.
    pub fn new(
        share_id: i64,
        share_code: String,
        server_name: String,
        password_required: bool,
    ) -> ConversationShareCreated {
        ConversationShareCreated {
            share_id,
            share_code,
            server_name,
            password_required,
            expires_at: None,
        }
    }
}
