/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateFileInput : CreateFileInput 的公开协议结构。 / Public contract for create file input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateFileInput {
    /// 文件名 / file name。
    #[serde(rename = "fileName")]
    pub file_name: String,
    /// 字段 contentMd5 / content md5 field。
    #[serde(rename = "contentMd5")]
    pub content_md5: String,
}

impl CreateFileInput {
    /// CreateFileInput 的公开协议结构。 / Public contract for create file input.
    pub fn new(file_name: String, content_md5: String) -> CreateFileInput {
        CreateFileInput {
            file_name,
            content_md5,
        }
    }
}
