/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DefaultModel : DefaultModel 的公开协议结构。 / Public contract for default model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefaultModel {
    /// 字段 keyGroupId / key group id field。
    #[serde(rename = "keyGroupId")]
    pub key_group_id: i64,
    /// 字段 model / model field。
    #[serde(rename = "model")]
    pub model: String,
}

impl DefaultModel {
    /// DefaultModel 的公开协议结构。 / Public contract for default model.
    pub fn new(key_group_id: i64, model: String) -> DefaultModel {
        DefaultModel {
            key_group_id,
            model,
        }
    }
}
