/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FieldError : FieldError 的公开协议结构。 / Public contract for field error.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldError {
    /// 字段 field / field field。
    #[serde(rename = "field")]
    pub field: String,
    /// 消息正文 / message text。
    #[serde(rename = "message")]
    pub message: String,
}

impl FieldError {
    /// FieldError 的公开协议结构。 / Public contract for field error.
    pub fn new(field: String, message: String) -> FieldError {
        FieldError { field, message }
    }
}
