/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileExists : FileExists 的公开协议结构。 / Public contract for file exists.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileExists {
    /// 字段 exists / exists field。
    #[serde(rename = "exists")]
    pub exists: bool,
}

impl FileExists {
    /// FileExists 的公开协议结构。 / Public contract for file exists.
    pub fn new(exists: bool) -> FileExists {
        FileExists { exists }
    }
}
