/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GeneratePreSignedUrlOutput : GeneratePreSignedUrlOutput 的公开协议结构。 / Public contract for generate pre signed url output.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeneratePreSignedUrlOutput {
    /// 当前存储是否支持该操作 / whether the storage supports this operation。
    #[serde(rename = "support")]
    pub support: bool,
    /// 字段 fileUk / file uk field。
    #[serde(
        rename = "fileUk",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub file_uk: Option<Option<String>>,
    /// 预签名 URL / presigned URL。
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
}

impl GeneratePreSignedUrlOutput {
    /// GeneratePreSignedUrlOutput 的公开协议结构。 / Public contract for generate pre signed url output.
    pub fn new(support: bool) -> GeneratePreSignedUrlOutput {
        GeneratePreSignedUrlOutput {
            support,
            file_uk: None,
            url: None,
        }
    }
}
