/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GeneratePreSignedUrlInput : GeneratePreSignedUrlInput 的公开协议结构。 / Public contract for generate pre signed url input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeneratePreSignedUrlInput {
    /// 文件名 / file name。
    #[serde(rename = "fileName")]
    pub file_name: String,
    /// 字段 module / module field。
    #[serde(rename = "module")]
    pub module: Module,
    /// 字段 contentMd5 / content md5 field。
    #[serde(rename = "contentMd5")]
    pub content_md5: String,
    /// 文件 ID / file ID。
    #[serde(
        rename = "fileId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub file_id: Option<Option<i64>>,
}

impl GeneratePreSignedUrlInput {
    /// GeneratePreSignedUrlInput 的公开协议结构。 / Public contract for generate pre signed url input.
    pub fn new(
        file_name: String,
        module: Module,
        content_md5: String,
    ) -> GeneratePreSignedUrlInput {
        GeneratePreSignedUrlInput {
            file_name,
            module,
            content_md5,
            file_id: None,
        }
    }
}
/// 字段 module / module field。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Module {
    #[serde(rename = "ai-chat-attachments")]
    AiChatAttachments,
}

impl Default for Module {
    fn default() -> Module {
        Self::AiChatAttachments
    }
}
