/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageGenerationExtensionContent : ImageGenerationExtensionContent 的公开协议结构。 / Public contract for image generation extension content.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageGenerationExtensionContent {
    /// 文件 ID / file ID。
    #[serde(rename = "fileId")]
    pub file_id: i64,
}

impl ImageGenerationExtensionContent {
    /// ImageGenerationExtensionContent 的公开协议结构。 / Public contract for image generation extension content.
    pub fn new(file_id: i64) -> ImageGenerationExtensionContent {
        ImageGenerationExtensionContent { file_id }
    }
}
