/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InputTokenBreakdown : InputTokenBreakdown 的公开协议结构。 / Public contract for input token breakdown.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputTokenBreakdown {
    /// 字段 observedInputTokens / observed input tokens field。
    #[serde(rename = "observedInputTokens")]
    pub observed_input_tokens: i64,
    /// 字段 uncachedInputTokens / uncached input tokens field。
    #[serde(rename = "uncachedInputTokens")]
    pub uncached_input_tokens: i64,
    /// 字段 cachedInputTokens / cached input tokens field。
    #[serde(rename = "cachedInputTokens")]
    pub cached_input_tokens: i64,
    /// 字段 cacheCreationInputTokens / cache creation input tokens field。
    #[serde(
        rename = "cacheCreationInputTokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_creation_input_tokens: Option<Option<i64>>,
}

impl InputTokenBreakdown {
    /// InputTokenBreakdown 的公开协议结构。 / Public contract for input token breakdown.
    pub fn new(
        observed_input_tokens: i64,
        uncached_input_tokens: i64,
        cached_input_tokens: i64,
    ) -> InputTokenBreakdown {
        InputTokenBreakdown {
            observed_input_tokens,
            uncached_input_tokens,
            cached_input_tokens,
            cache_creation_input_tokens: None,
        }
    }
}
