/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IntegerChartColumn : IntegerChartColumn 的公开协议结构。 / Public contract for integer chart column.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegerChartColumn {
    /// 字段 name / name field。
    #[serde(rename = "name")]
    pub name: String,
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 values / values field。
    #[serde(rename = "values")]
    pub values: Vec<i64>,
}

impl IntegerChartColumn {
    /// IntegerChartColumn 的公开协议结构。 / Public contract for integer chart column.
    pub fn new(name: String, r#type: Type, values: Vec<i64>) -> IntegerChartColumn {
        IntegerChartColumn {
            name,
            r#type,
            values,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "INTEGER")]
    Integer,
    #[serde(rename = "LONG")]
    Long,
}

impl Default for Type {
    fn default() -> Type {
        Self::Integer
    }
}
