/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsRunScriptExtensionContent : JsRunScriptExtensionContent 的公开协议结构。 / Public contract for js run script extension content.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsRunScriptExtensionContent {
    /// 字段 script / script field。
    #[serde(rename = "script")]
    pub script: String,
}

impl JsRunScriptExtensionContent {
    /// JsRunScriptExtensionContent 的公开协议结构。 / Public contract for js run script extension content.
    pub fn new(script: String) -> JsRunScriptExtensionContent {
        JsRunScriptExtensionContent { script }
    }
}
