/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MathFormulaExtensionContent : MathFormulaExtensionContent 的公开协议结构。 / Public contract for math formula extension content.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MathFormulaExtensionContent {
    /// 字段 expression / expression field。
    #[serde(rename = "expression")]
    pub expression: String,
    /// 字段 variables / variables field。
    #[serde(
        rename = "variables",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub variables: Option<Option<Vec<models::VariableBinding>>>,
}

impl MathFormulaExtensionContent {
    /// MathFormulaExtensionContent 的公开协议结构。 / Public contract for math formula extension content.
    pub fn new(expression: String) -> MathFormulaExtensionContent {
        MathFormulaExtensionContent {
            expression,
            variables: None,
        }
    }
}
