/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MediaAttachment : MediaAttachment 的公开协议结构。 / Public contract for media attachment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaAttachment {
    /// 文件 ID / file ID。
    #[serde(rename = "fileId")]
    pub file_id: i64,
    /// 字段 path / path field。
    #[serde(rename = "path")]
    pub path: String,
    /// 字段 fileSize / file size field。
    #[serde(rename = "fileSize")]
    pub file_size: i64,
    /// 文件名 / file name。
    #[serde(rename = "fileName")]
    pub file_name: String,
    /// MIME 类型 / MIME type。
    #[serde(rename = "mimeType")]
    pub mime_type: String,
}

impl MediaAttachment {
    /// MediaAttachment 的公开协议结构。 / Public contract for media attachment.
    pub fn new(
        file_id: i64,
        path: String,
        file_size: i64,
        file_name: String,
        mime_type: String,
    ) -> MediaAttachment {
        MediaAttachment {
            file_id,
            path,
            file_size,
            file_name,
            mime_type,
        }
    }
}
