/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModelKeyGroup : ModelKeyGroup 的公开协议结构。 / Public contract for model key group.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelKeyGroup {
    /// 字段 keyGroupId / key group id field。
    #[serde(rename = "keyGroupId")]
    pub key_group_id: i64,
    /// 字段 keyGroupName / key group name field。
    #[serde(rename = "keyGroupName")]
    pub key_group_name: String,
    /// 字段 models / models field。
    #[serde(rename = "models")]
    pub models: Vec<models::ChatModelConfig>,
}

impl ModelKeyGroup {
    /// ModelKeyGroup 的公开协议结构。 / Public contract for model key group.
    pub fn new(
        key_group_id: i64,
        key_group_name: String,
        models: Vec<models::ChatModelConfig>,
    ) -> ModelKeyGroup {
        ModelKeyGroup {
            key_group_id,
            key_group_name,
            models,
        }
    }
}
