/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModelConfig : ModelConfig 的公开协议结构。 / Public contract for model config.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelConfig {
    /// 字段 defaultModel / default model field。
    #[serde(rename = "defaultModel", deserialize_with = "Option::deserialize")]
    pub default_model: Option<Box<models::DefaultModel>>,
    /// 字段 modelKeyGroups / model key groups field。
    #[serde(rename = "modelKeyGroups")]
    pub model_key_groups: Vec<models::ModelKeyGroup>,
}

impl ModelConfig {
    /// ModelConfig 的公开协议结构。 / Public contract for model config.
    pub fn new(
        default_model: Option<models::DefaultModel>,
        model_key_groups: Vec<models::ModelKeyGroup>,
    ) -> ModelConfig {
        ModelConfig {
            default_model: if let Some(x) = default_model {
                Some(Box::new(x))
            } else {
                None
            },
            model_key_groups,
        }
    }
}
