/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MultimodalMediaAttachment : MultimodalMediaAttachment 的公开协议结构。 / Public contract for multimodal media attachment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultimodalMediaAttachment {
    /// 文件名 / file name。
    #[serde(rename = "fileName")]
    pub file_name: String,
    /// MIME 类型 / MIME type。
    #[serde(rename = "mimeType")]
    pub mime_type: String,
    /// 字段 data / data field。
    #[serde(rename = "data")]
    pub data: String,
}

impl MultimodalMediaAttachment {
    /// MultimodalMediaAttachment 的公开协议结构。 / Public contract for multimodal media attachment.
    pub fn new(file_name: String, mime_type: String, data: String) -> MultimodalMediaAttachment {
        MultimodalMediaAttachment {
            file_name,
            mime_type,
            data,
        }
    }
}
