/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PageInfo : PageInfo 的公开协议结构。 / Public contract for page info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageInfo {
    /// 字段 current / current field。
    #[serde(rename = "current")]
    pub current: i32,
    /// 大小（字节）或分页容量 / byte size or page size。
    #[serde(rename = "size")]
    pub size: i32,
    /// 字段 total / total field。
    #[serde(rename = "total")]
    pub total: i64,
}

impl PageInfo {
    /// PageInfo 的公开协议结构。 / Public contract for page info.
    pub fn new(current: i32, size: i32, total: i64) -> PageInfo {
        PageInfo {
            current,
            size,
            total,
        }
    }
}
