/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlanApprovalExtensionContent : PlanApprovalExtensionContent 的公开协议结构。 / Public contract for plan approval extension content.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanApprovalExtensionContent {
    /// 字段 previewFileId / preview file id field。
    #[serde(rename = "previewFileId")]
    pub preview_file_id: i64,
    /// 字段 serverNow / server now field。
    #[serde(rename = "serverNow")]
    pub server_now: chrono::DateTime<chrono::FixedOffset>,
    /// 字段 approvalTimeoutAt / approval timeout at field。
    #[serde(rename = "approvalTimeoutAt")]
    pub approval_timeout_at: chrono::DateTime<chrono::FixedOffset>,
}

impl PlanApprovalExtensionContent {
    /// PlanApprovalExtensionContent 的公开协议结构。 / Public contract for plan approval extension content.
    pub fn new(
        preview_file_id: i64,
        server_now: chrono::DateTime<chrono::FixedOffset>,
        approval_timeout_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> PlanApprovalExtensionContent {
        PlanApprovalExtensionContent {
            preview_file_id,
            server_now,
            approval_timeout_at,
        }
    }
}
