/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlanApprovalInput : PlanApprovalInput 的公开协议结构。 / Public contract for plan approval input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanApprovalInput {
    /// 会话 ID / conversation ID。
    #[serde(rename = "conversationId")]
    pub conversation_id: String,
    /// 消息 ID / message ID。
    #[serde(rename = "messageId")]
    pub message_id: String,
    /// 字段 approved / approved field。
    #[serde(rename = "approved")]
    pub approved: bool,
    /// 字段 feedback / feedback field。
    #[serde(
        rename = "feedback",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub feedback: Option<Option<String>>,
}

impl PlanApprovalInput {
    /// PlanApprovalInput 的公开协议结构。 / Public contract for plan approval input.
    pub fn new(conversation_id: String, message_id: String, approved: bool) -> PlanApprovalInput {
        PlanApprovalInput {
            conversation_id,
            message_id,
            approved,
            feedback: None,
        }
    }
}
