/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlanStatus : PlanStatus 的公开协议结构。 / Public contract for plan status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanStatus {
    /// 字段 pending / pending field。
    #[serde(rename = "pending")]
    pub pending: bool,
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
}

impl PlanStatus {
    /// PlanStatus 的公开协议结构。 / Public contract for plan status.
    pub fn new(pending: bool, status: String) -> PlanStatus {
        PlanStatus { pending, status }
    }
}
