/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PreSignedReadUrl : PreSignedReadUrl 的公开协议结构。 / Public contract for pre signed read url.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreSignedReadUrl {
    /// 预签名 URL / presigned URL。
    #[serde(rename = "url")]
    pub url: String,
}

impl PreSignedReadUrl {
    /// PreSignedReadUrl 的公开协议结构。 / Public contract for pre signed read url.
    pub fn new(url: String) -> PreSignedReadUrl {
        PreSignedReadUrl { url }
    }
}
