/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReturnedReference : ReturnedReference 的公开协议结构。 / Public contract for returned reference.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReturnedReference {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: String,
    /// 字段 referenceId / reference id field。
    #[serde(rename = "referenceId")]
    pub reference_id: i64,
}

impl ReturnedReference {
    /// ReturnedReference 的公开协议结构。 / Public contract for returned reference.
    pub fn new(r#type: String, reference_id: i64) -> ReturnedReference {
        ReturnedReference {
            r#type,
            reference_id,
        }
    }
}
