/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SkillResourceExtensionContent : SkillResourceExtensionContent 的公开协议结构。 / Public contract for skill resource extension content.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SkillResourceExtensionContent {
    /// 字段 operationType / operation type field。
    #[serde(rename = "operationType")]
    pub operation_type: String,
    /// 字段 filepath / filepath field。
    #[serde(rename = "filepath")]
    pub filepath: String,
}

impl SkillResourceExtensionContent {
    /// SkillResourceExtensionContent 的公开协议结构。 / Public contract for skill resource extension content.
    pub fn new(operation_type: String, filepath: String) -> SkillResourceExtensionContent {
        SkillResourceExtensionContent {
            operation_type,
            filepath,
        }
    }
}
