/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SqlQueryExtensionContent : SqlQueryExtensionContent 的公开协议结构。 / Public contract for sql query extension content.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SqlQueryExtensionContent {
    /// 字段 sql / sql field。
    #[serde(rename = "sql")]
    pub sql: String,
}

impl SqlQueryExtensionContent {
    /// SqlQueryExtensionContent 的公开协议结构。 / Public contract for sql query extension content.
    pub fn new(sql: String) -> SqlQueryExtensionContent {
        SqlQueryExtensionContent { sql }
    }
}
