/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SqlQueryExtensionToolExtension : SqlQueryExtensionToolExtension 的公开协议结构。 / Public contract for sql query extension tool extension.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SqlQueryExtensionToolExtension {
    /// 扩展类别判别值 / extension category discriminator。
    #[serde(rename = "category")]
    pub category: Category,
    /// 与类别对应的强类型内容 / strongly typed content for the category。
    #[serde(rename = "content")]
    pub content: Box<models::SqlQueryExtensionContent>,
    /// 是否使用独立视图渲染 / whether to use a dedicated view。
    #[serde(rename = "specialRender")]
    pub special_render: bool,
}

impl SqlQueryExtensionToolExtension {
    /// SqlQueryExtensionToolExtension 的公开协议结构。 / Public contract for sql query extension tool extension.
    pub fn new(
        category: Category,
        content: models::SqlQueryExtensionContent,
        special_render: bool,
    ) -> SqlQueryExtensionToolExtension {
        SqlQueryExtensionToolExtension {
            category,
            content: Box::new(content),
            special_render,
        }
    }
}
/// 扩展类别判别值 / extension category discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Category {
    #[serde(rename = "sqlQuery")]
    SqlQuery,
}

impl Default for Category {
    fn default() -> Category {
        Self::SqlQuery
    }
}
