/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubagentTask : SubagentTask 的公开协议结构。 / Public contract for subagent task.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubagentTask {
    /// 异步任务 ID / asynchronous task ID。
    #[serde(rename = "taskId")]
    pub task_id: String,
    /// 可读说明 / human-readable description。
    #[serde(rename = "description")]
    pub description: String,
    /// 字段 subagentType / subagent type field。
    #[serde(rename = "subagentType")]
    pub subagent_type: String,
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
    /// 字段 phase / phase field。
    #[serde(
        rename = "phase",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phase: Option<Option<String>>,
    /// 字段 progressPercent / progress percent field。
    #[serde(
        rename = "progressPercent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub progress_percent: Option<Option<i32>>,
    /// 字段 parentConversationId / parent conversation id field。
    #[serde(rename = "parentConversationId")]
    pub parent_conversation_id: String,
    /// 字段 parentMessageId / parent message id field。
    #[serde(rename = "parentMessageId")]
    pub parent_message_id: String,
    /// 字段 childConversationId / child conversation id field。
    #[serde(
        rename = "childConversationId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub child_conversation_id: Option<Option<String>>,
    /// 字段 childMessageId / child message id field。
    #[serde(
        rename = "childMessageId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub child_message_id: Option<Option<String>>,
    /// 字段 resultAvailable / result available field。
    #[serde(rename = "resultAvailable")]
    pub result_available: bool,
    /// 字段 artifactCount / artifact count field。
    #[serde(rename = "artifactCount")]
    pub artifact_count: i32,
    /// 字段 notificationStatus / notification status field。
    #[serde(rename = "notificationStatus")]
    pub notification_status: String,
    /// 字段 failureCode / failure code field。
    #[serde(
        rename = "failureCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub failure_code: Option<Option<String>>,
    /// 字段 failureMessage / failure message field。
    #[serde(
        rename = "failureMessage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub failure_message: Option<Option<String>>,
    /// 创建时间 / creation time。
    #[serde(rename = "createdTime")]
    pub created_time: chrono::DateTime<chrono::FixedOffset>,
    /// 字段 startedTime / started time field。
    #[serde(
        rename = "startedTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub started_time: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// 字段 completedTime / completed time field。
    #[serde(
        rename = "completedTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub completed_time: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// 最后更新时间 / last update time。
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
    /// 字段 cancellable / cancellable field。
    #[serde(rename = "cancellable")]
    pub cancellable: bool,
}

impl SubagentTask {
    /// SubagentTask 的公开协议结构。 / Public contract for subagent task.
    pub fn new(
        task_id: String,
        description: String,
        subagent_type: String,
        status: String,
        parent_conversation_id: String,
        parent_message_id: String,
        result_available: bool,
        artifact_count: i32,
        notification_status: String,
        created_time: chrono::DateTime<chrono::FixedOffset>,
        last_update_time: chrono::DateTime<chrono::FixedOffset>,
        cancellable: bool,
    ) -> SubagentTask {
        SubagentTask {
            task_id,
            description,
            subagent_type,
            status,
            phase: None,
            progress_percent: None,
            parent_conversation_id,
            parent_message_id,
            child_conversation_id: None,
            child_message_id: None,
            result_available,
            artifact_count,
            notification_status,
            failure_code: None,
            failure_message: None,
            created_time,
            started_time: None,
            completed_time: None,
            last_update_time,
            cancellable,
        }
    }
}
