/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SystemChatMessage : SystemChatMessage 的公开协议结构。 / Public contract for system chat message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemChatMessage {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 text / text field。
    #[serde(rename = "text")]
    pub text: String,
    /// 字段 metadataRawJson / metadata raw json field。
    #[serde(
        rename = "metadataRawJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub metadata_raw_json: Option<Option<String>>,
}

impl SystemChatMessage {
    /// SystemChatMessage 的公开协议结构。 / Public contract for system chat message.
    pub fn new(r#type: Type, text: String) -> SystemChatMessage {
        SystemChatMessage {
            r#type,
            text,
            metadata_raw_json: None,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "SYSTEM")]
    System,
}

impl Default for Type {
    fn default() -> Type {
        Self::System
    }
}
