/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskSummary : TaskSummary 的公开协议结构。 / Public contract for task summary.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskSummary {
    /// 字段 id / id field。
    #[serde(rename = "id")]
    pub id: String,
    /// 字段 subject / subject field。
    #[serde(rename = "subject")]
    pub subject: String,
    /// 字段 activeForm / active form field。
    #[serde(
        rename = "activeForm",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub active_form: Option<Option<String>>,
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
    /// 字段 blocks / blocks field。
    #[serde(rename = "blocks")]
    pub blocks: Vec<String>,
    /// 字段 blockedBy / blocked by field。
    #[serde(rename = "blockedBy")]
    pub blocked_by: Vec<String>,
}

impl TaskSummary {
    /// TaskSummary 的公开协议结构。 / Public contract for task summary.
    pub fn new(
        id: String,
        subject: String,
        status: String,
        blocks: Vec<String>,
        blocked_by: Vec<String>,
    ) -> TaskSummary {
        TaskSummary {
            id,
            subject,
            active_form: None,
            status,
            blocks,
            blocked_by,
        }
    }
}
