/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskProgressExtensionContent : TaskProgressExtensionContent 的公开协议结构。 / Public contract for task progress extension content.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskProgressExtensionContent {
    /// 字段 action / action field。
    #[serde(rename = "action")]
    pub action: String,
    /// 字段 currentTaskId / current task id field。
    #[serde(
        rename = "currentTaskId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub current_task_id: Option<Option<String>>,
    /// 字段 currentTaskStatus / current task status field。
    #[serde(
        rename = "currentTaskStatus",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub current_task_status: Option<Option<String>>,
    /// 字段 archived / archived field。
    #[serde(rename = "archived")]
    pub archived: bool,
    /// 字段 total / total field。
    #[serde(rename = "total")]
    pub total: i32,
    /// 字段 pending / pending field。
    #[serde(rename = "pending")]
    pub pending: i32,
    /// 字段 inProgress / in progress field。
    #[serde(rename = "inProgress")]
    pub in_progress: i32,
    /// 字段 completed / completed field。
    #[serde(rename = "completed")]
    pub completed: i32,
    /// 字段 progressPercent / progress percent field。
    #[serde(rename = "progressPercent")]
    pub progress_percent: i32,
    /// 字段 tasks / tasks field。
    #[serde(rename = "tasks")]
    pub tasks: Vec<models::TaskSummary>,
}

impl TaskProgressExtensionContent {
    /// TaskProgressExtensionContent 的公开协议结构。 / Public contract for task progress extension content.
    pub fn new(
        action: String,
        archived: bool,
        total: i32,
        pending: i32,
        in_progress: i32,
        completed: i32,
        progress_percent: i32,
        tasks: Vec<models::TaskSummary>,
    ) -> TaskProgressExtensionContent {
        TaskProgressExtensionContent {
            action,
            current_task_id: None,
            current_task_status: None,
            archived,
            total,
            pending,
            in_progress,
            completed,
            progress_percent,
            tasks,
        }
    }
}
