/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskProgressExtensionContent : TaskProgressExtensionContent 的公开协议结构。 / Public contract for task progress extension content.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskProgressExtensionContent {
    /// 字段 action / action field。
    #[serde(rename = "action")]
    pub action: String,
    /// 字段 currentTaskId / current task id field。
    #[serde(
        rename = "currentTaskId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub current_task_id: Option<Option<String>>,
    /// 字段 currentTaskStatus / current task status field。
    #[serde(
        rename = "currentTaskStatus",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub current_task_status: Option<Option<String>>,
    /// 字段 archived / archived field。
    #[serde(rename = "archived")]
    pub archived: bool,
    /// 字段 total / total field。
    #[serde(rename = "total")]
    pub total: i32,
    /// 字段 pending / pending field。
    #[serde(rename = "pending")]
    pub pending: i32,
    /// 字段 inProgress / in progress field。
    #[serde(rename = "inProgress")]
    pub in_progress: i32,
    /// 字段 completed / completed field。
    #[serde(rename = "completed")]
    pub completed: i32,
    /// 字段 progressPercent / progress percent field。
    #[serde(rename = "progressPercent")]
    pub progress_percent: i32,
    /// 字段 tasks / tasks field。
    #[serde(rename = "tasks")]
    pub tasks: Vec<models::TaskSummary>,
}

impl TaskProgressExtensionContent {
    /// TaskProgressExtensionContent 的公开协议结构。 / Public contract for task progress extension content.
    pub fn new(
        action: String,
        archived: bool,
        total: i32,
        pending: i32,
        in_progress: i32,
        completed: i32,
        progress_percent: i32,
        tasks: Vec<models::TaskSummary>,
    ) -> TaskProgressExtensionContent {
        TaskProgressExtensionContent {
            action,
            current_task_id: None,
            current_task_status: None,
            archived,
            total,
            pending,
            in_progress,
            completed,
            progress_percent,
            tasks,
        }
    }
}
