/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ToolCall : ToolCall 的公开协议结构。 / Public contract for tool call.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolCall {
    /// 字段 id / id field。
    #[serde(rename = "id")]
    pub id: String,
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: String,
    /// 字段 name / name field。
    #[serde(rename = "name")]
    pub name: String,
    /// 字段 arguments / arguments field。
    #[serde(rename = "arguments")]
    pub arguments: String,
}

impl ToolCall {
    /// ToolCall 的公开协议结构。 / Public contract for tool call.
    pub fn new(id: String, r#type: String, name: String, arguments: String) -> ToolCall {
        ToolCall {
            id,
            r#type,
            name,
            arguments,
        }
    }
}
