/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ToolResponseChatMessage : ToolResponseChatMessage 的公开协议结构。 / Public contract for tool response chat message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolResponseChatMessage {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 responses / responses field。
    #[serde(rename = "responses")]
    pub responses: Vec<models::ToolResponse>,
    /// 字段 metadataRawJson / metadata raw json field。
    #[serde(
        rename = "metadataRawJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub metadata_raw_json: Option<Option<String>>,
}

impl ToolResponseChatMessage {
    /// ToolResponseChatMessage 的公开协议结构。 / Public contract for tool response chat message.
    pub fn new(r#type: Type, responses: Vec<models::ToolResponse>) -> ToolResponseChatMessage {
        ToolResponseChatMessage {
            r#type,
            responses,
            metadata_raw_json: None,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "TOOL")]
    Tool,
}

impl Default for Type {
    fn default() -> Type {
        Self::Tool
    }
}
