/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ToolResponse : ToolResponse 的公开协议结构。 / Public contract for tool response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolResponse {
    /// 字段 id / id field。
    #[serde(rename = "id")]
    pub id: String,
    /// 字段 name / name field。
    #[serde(rename = "name")]
    pub name: String,
    /// 当前状态 / current status。
    #[serde(rename = "status")]
    pub status: String,
    /// 字段 responseData / response data field。
    #[serde(rename = "responseData")]
    pub response_data: String,
    /// 字段 metadataRawJson / metadata raw json field。
    #[serde(rename = "metadataRawJson")]
    pub metadata_raw_json: String,
}

impl ToolResponse {
    /// ToolResponse 的公开协议结构。 / Public contract for tool response.
    pub fn new(
        id: String,
        name: String,
        status: String,
        response_data: String,
        metadata_raw_json: String,
    ) -> ToolResponse {
        ToolResponse {
            id,
            name,
            status,
            response_data,
            metadata_raw_json,
        }
    }
}
