/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ToolExtension : ToolExtension 的公开协议结构。 / Public contract for tool extension.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "category")]
pub enum ToolExtension {
    #[serde(rename = "planApproval")]
    PlanApproval(Box<models::PlanApprovalExtensionToolExtension>),
    #[serde(rename = "askUserQuestion")]
    AskUserQuestion(Box<models::AskUserQuestionExtensionToolExtension>),
    #[serde(rename = "imageGeneration")]
    ImageGeneration(Box<models::ImageGenerationExtensionToolExtension>),
    #[serde(rename = "sqlQuery")]
    SqlQuery(Box<models::SqlQueryExtensionToolExtension>),
    #[serde(rename = "sqlQueryResult")]
    SqlQueryResult(Box<models::SqlQueryResultExtensionToolExtension>),
    #[serde(rename = "sqlChartResult")]
    SqlChartResult(Box<models::SqlChartResultExtensionToolExtension>),
    #[serde(rename = "mathFormula")]
    MathFormula(Box<models::MathFormulaExtensionToolExtension>),
    #[serde(rename = "mathResult")]
    MathResult(Box<models::MathResultExtensionToolExtension>),
    #[serde(rename = "jsRunScript")]
    JsRunScript(Box<models::JsRunScriptExtensionToolExtension>),
    #[serde(rename = "jsRunScriptResult")]
    JsRunScriptResult(Box<models::JsRunScriptResultExtensionToolExtension>),
    #[serde(rename = "skillResource")]
    SkillResource(Box<models::SkillResourceExtensionToolExtension>),
    #[serde(rename = "taskProgress")]
    TaskProgress(Box<models::TaskProgressExtensionToolExtension>),
    #[serde(rename = "UnknownToolExtension")]
    UnknownToolExtension(Box<models::UnknownToolExtension>),
}

impl Default for ToolExtension {
    fn default() -> Self {
        Self::PlanApproval(Default::default())
    }
}
