/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnknownToolExtension : UnknownToolExtension 的公开协议结构。 / Public contract for unknown tool extension.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnknownToolExtension {
    /// 扩展类别判别值 / extension category discriminator。
    #[serde(rename = "category")]
    pub category: String,
    /// 未识别对象的原始 JSON / raw JSON for an unrecognized object。
    #[serde(rename = "rawJson")]
    pub raw_json: String,
}

impl UnknownToolExtension {
    /// UnknownToolExtension 的公开协议结构。 / Public contract for unknown tool extension.
    pub fn new(category: String, raw_json: String) -> UnknownToolExtension {
        UnknownToolExtension { category, raw_json }
    }
}
