/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnknownAiChatBriefEvent : UnknownAiChatBriefEvent 的公开协议结构。 / Public contract for unknown ai chat brief event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnknownAiChatBriefEvent {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: String,
    /// 未识别对象的原始 JSON / raw JSON for an unrecognized object。
    #[serde(rename = "rawJson")]
    pub raw_json: String,
}

impl UnknownAiChatBriefEvent {
    /// UnknownAiChatBriefEvent 的公开协议结构。 / Public contract for unknown ai chat brief event.
    pub fn new(r#type: String, raw_json: String) -> UnknownAiChatBriefEvent {
        UnknownAiChatBriefEvent { r#type, raw_json }
    }
}
