/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Usage : Usage 的公开协议结构。 / Public contract for usage.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Usage {
    /// 输入 Token 数 / input token count。
    #[serde(rename = "inputTokens")]
    pub input_tokens: i64,
    /// 输出 Token 数 / output token count。
    #[serde(rename = "outputTokens")]
    pub output_tokens: i64,
    /// 总 Token 数 / total token count。
    #[serde(rename = "totalTokens")]
    pub total_tokens: i64,
    /// 字段 inputTokenBreakdown / input token breakdown field。
    #[serde(
        rename = "inputTokenBreakdown",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_token_breakdown: Option<Option<Box<models::InputTokenBreakdown>>>,
    /// 字段 reasoningTokens / reasoning tokens field。
    #[serde(
        rename = "reasoningTokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reasoning_tokens: Option<Option<i64>>,
    /// 字段 cacheHitRate / cache hit rate field。
    #[serde(
        rename = "cacheHitRate",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_hit_rate: Option<Option<f64>>,
    /// 字段 inputBreakdownCoverageRate / input breakdown coverage rate field。
    #[serde(
        rename = "inputBreakdownCoverageRate",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_breakdown_coverage_rate: Option<Option<f64>>,
}

impl Usage {
    /// Usage 的公开协议结构。 / Public contract for usage.
    pub fn new(input_tokens: i64, output_tokens: i64, total_tokens: i64) -> Usage {
        Usage {
            input_tokens,
            output_tokens,
            total_tokens,
            input_token_breakdown: None,
            reasoning_tokens: None,
            cache_hit_rate: None,
            input_breakdown_coverage_rate: None,
        }
    }
}
