/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserInputStatus : UserInputStatus 的公开协议结构。 / Public contract for user input status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserInputStatus {
    /// 字段 pending / pending field。
    #[serde(rename = "pending")]
    pub pending: bool,
    /// 字段 question / question field。
    #[serde(
        rename = "question",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub question: Option<Option<String>>,
    /// 字段 questionDetails / question details field。
    #[serde(
        rename = "questionDetails",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub question_details: Option<Option<String>>,
    /// 字段 options / options field。
    #[serde(
        rename = "options",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub options: Option<Option<Vec<String>>>,
    /// 字段 multiple / multiple field。
    #[serde(
        rename = "multiple",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub multiple: Option<Option<bool>>,
}

impl UserInputStatus {
    /// UserInputStatus 的公开协议结构。 / Public contract for user input status.
    pub fn new(pending: bool) -> UserInputStatus {
        UserInputStatus {
            pending,
            question: None,
            question_details: None,
            options: None,
            multiple: None,
        }
    }
}
