/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserChatMessage : UserChatMessage 的公开协议结构。 / Public contract for user chat message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserChatMessage {
    /// 类型判别值 / type discriminator。
    #[serde(rename = "type")]
    pub r#type: Type,
    /// 字段 text / text field。
    #[serde(rename = "text")]
    pub text: String,
    /// 字段 multimodalAttachments / multimodal attachments field。
    #[serde(
        rename = "multimodalAttachments",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub multimodal_attachments: Option<Option<Vec<models::MultimodalMediaAttachment>>>,
    /// 字段 attachments / attachments field。
    #[serde(
        rename = "attachments",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub attachments: Option<Option<Vec<models::MediaAttachment>>>,
    /// 字段 metadataRawJson / metadata raw json field。
    #[serde(
        rename = "metadataRawJson",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub metadata_raw_json: Option<Option<String>>,
}

impl UserChatMessage {
    /// UserChatMessage 的公开协议结构。 / Public contract for user chat message.
    pub fn new(r#type: Type, text: String) -> UserChatMessage {
        UserChatMessage {
            r#type,
            text,
            multimodal_attachments: None,
            attachments: None,
            metadata_raw_json: None,
        }
    }
}
/// 类型判别值 / type discriminator。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "USER")]
    User,
}

impl Default for Type {
    fn default() -> Type {
        Self::User
    }
}
