/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserInputAnswerInput : UserInputAnswerInput 的公开协议结构。 / Public contract for user input answer input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserInputAnswerInput {
    /// 会话 ID / conversation ID。
    #[serde(rename = "conversationId")]
    pub conversation_id: String,
    /// 消息 ID / message ID。
    #[serde(rename = "messageId")]
    pub message_id: String,
    /// 字段 questionId / question id field。
    #[serde(rename = "questionId")]
    pub question_id: String,
    /// 字段 selectedOptions / selected options field。
    #[serde(rename = "selectedOptions")]
    pub selected_options: Vec<String>,
    /// 字段 customInput / custom input field。
    #[serde(
        rename = "customInput",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_input: Option<Option<String>>,
}

impl UserInputAnswerInput {
    /// UserInputAnswerInput 的公开协议结构。 / Public contract for user input answer input.
    pub fn new(
        conversation_id: String,
        message_id: String,
        question_id: String,
        selected_options: Vec<String>,
    ) -> UserInputAnswerInput {
        UserInputAnswerInput {
            conversation_id,
            message_id,
            question_id,
            selected_options,
            custom_input: None,
        }
    }
}
