/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidationError : ValidationError 的公开协议结构。 / Public contract for validation error.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationError {
    /// 字段 code / code field。
    #[serde(rename = "code")]
    pub code: String,
    /// 消息正文 / message text。
    #[serde(rename = "message")]
    pub message: String,
    /// 字段 fields / fields field。
    #[serde(rename = "fields")]
    pub fields: Vec<models::FieldError>,
}

impl ValidationError {
    /// ValidationError 的公开协议结构。 / Public contract for validation error.
    pub fn new(code: String, message: String, fields: Vec<models::FieldError>) -> ValidationError {
        ValidationError {
            code,
            message,
            fields,
        }
    }
}
