/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VariableBinding : VariableBinding 的公开协议结构。 / Public contract for variable binding.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariableBinding {
    /// 字段 name / name field。
    #[serde(rename = "name")]
    pub name: String,
    /// 字段 value / value field。
    #[serde(rename = "value")]
    pub value: String,
}

impl VariableBinding {
    /// VariableBinding 的公开协议结构。 / Public contract for variable binding.
    pub fn new(name: String, value: String) -> VariableBinding {
        VariableBinding { name, value }
    }
}
