/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceFilePage : WorkspaceFilePage 的公开协议结构。 / Public contract for workspace file page.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceFilePage {
    /// 记录列表 / records。
    #[serde(rename = "records")]
    pub records: Vec<models::WorkspaceFile>,
    /// 分页信息 / page metadata。
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
}

impl WorkspaceFilePage {
    /// WorkspaceFilePage 的公开协议结构。 / Public contract for workspace file page.
    pub fn new(records: Vec<models::WorkspaceFile>, page: models::PageInfo) -> WorkspaceFilePage {
        WorkspaceFilePage {
            records,
            page: Box::new(page),
        }
    }
}
