/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceArtifactList : WorkspaceArtifactList 的公开协议结构。 / Public contract for workspace artifact list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceArtifactList {
    /// 字段 fileArtifacts / file artifacts field。
    #[serde(rename = "fileArtifacts")]
    pub file_artifacts: Box<models::WorkspaceFilePage>,
    /// 字段 nonFileArtifacts / non file artifacts field。
    #[serde(rename = "nonFileArtifacts")]
    pub non_file_artifacts: Vec<models::WorkspaceNonFileArtifact>,
}

impl WorkspaceArtifactList {
    /// WorkspaceArtifactList 的公开协议结构。 / Public contract for workspace artifact list.
    pub fn new(
        file_artifacts: models::WorkspaceFilePage,
        non_file_artifacts: Vec<models::WorkspaceNonFileArtifact>,
    ) -> WorkspaceArtifactList {
        WorkspaceArtifactList {
            file_artifacts: Box::new(file_artifacts),
            non_file_artifacts,
        }
    }
}
