/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceFile : WorkspaceFile 的公开协议结构。 / Public contract for workspace file.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceFile {
    /// 字段 relativePath / relative path field。
    #[serde(rename = "relativePath")]
    pub relative_path: String,
    /// 大小（字节）或分页容量 / byte size or page size。
    #[serde(rename = "size")]
    pub size: i64,
    /// 文件名 / file name。
    #[serde(rename = "fileName")]
    pub file_name: String,
    /// MIME 类型 / MIME type。
    #[serde(rename = "mimeType")]
    pub mime_type: String,
    /// 最后更新时间 / last update time。
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
}

impl WorkspaceFile {
    /// WorkspaceFile 的公开协议结构。 / Public contract for workspace file.
    pub fn new(
        relative_path: String,
        size: i64,
        file_name: String,
        mime_type: String,
        last_update_time: chrono::DateTime<chrono::FixedOffset>,
    ) -> WorkspaceFile {
        WorkspaceFile {
            relative_path,
            size,
            file_name,
            mime_type,
            last_update_time,
        }
    }
}
