/*
 * Lingya Agents OpenAPI
 *
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceFile : WorkspaceFile 的公开协议结构。 / Public contract for workspace file.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceFile {
    /// 字段 relativePath / relative path field。
    #[serde(rename = "relativePath")]
    pub relative_path: String,
    /// 大小（字节）或分页容量 / byte size or page size。
    #[serde(rename = "size")]
    pub size: i64,
    /// 文件名 / file name。
    #[serde(rename = "fileName")]
    pub file_name: String,
    /// MIME 类型 / MIME type。
    #[serde(rename = "mimeType")]
    pub mime_type: String,
    /// 最后更新时间 / last update time。
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
}

impl WorkspaceFile {
    /// WorkspaceFile 的公开协议结构。 / Public contract for workspace file.
    pub fn new(
        relative_path: String,
        size: i64,
        file_name: String,
        mime_type: String,
        last_update_time: chrono::DateTime<chrono::FixedOffset>,
    ) -> WorkspaceFile {
        WorkspaceFile {
            relative_path,
            size,
            file_name,
            mime_type,
            last_update_time,
        }
    }
}
