/*
 * Lingya Agents OpenAPI
 *
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceNonFileArtifact : WorkspaceNonFileArtifact 的公开协议结构。 / Public contract for workspace non file artifact.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceNonFileArtifact {
    /// 字段 artifactId / artifact id field。
    #[serde(rename = "artifactId")]
    pub artifact_id: String,
    /// 字段 kind / kind field。
    #[serde(rename = "kind")]
    pub kind: String,
    /// 标题 / title。
    #[serde(rename = "title")]
    pub title: String,
    /// 可读说明 / human-readable description。
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// 最后更新时间 / last update time。
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
    /// 字段 previewUrl / preview url field。
    #[serde(
        rename = "previewUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub preview_url: Option<Option<String>>,
}

impl WorkspaceNonFileArtifact {
    /// WorkspaceNonFileArtifact 的公开协议结构。 / Public contract for workspace non file artifact.
    pub fn new(
        artifact_id: String,
        kind: String,
        title: String,
        last_update_time: chrono::DateTime<chrono::FixedOffset>,
    ) -> WorkspaceNonFileArtifact {
        WorkspaceNonFileArtifact {
            artifact_id,
            kind,
            title,
            description: None,
            last_update_time,
            preview_url: None,
        }
    }
}
